#!/usr/bin/env python3
import os
import sys
from build_all_showcases import (
    render_showcase, 
    C_TEXT_WHITE, C_TEXT_DIM, C_TEXT_MUTED, C_BLUE, C_CYAN, 
    C_GREEN, C_YELLOW, C_RED, C_PURPLE, C_ORANGE
)

PROJECTS_DATA = {
    "lbr-telemetry": {
        "title": "lbr_ground — Lunar Mission SDR & Real-Time Telemetry Pipeline",
        "subtitle": "433.92 MHz SX1262 LoRa Telemetry Stream",
        "badge": "● SDR STREAM ACTIVE",
        "badge_color": C_CYAN,
        "dir": "~/Bureau/Long-Beach-Rocketry/build-linux/LoRa",
        "cmd": "./lbr_ground -b virtual -v",
        "lines": [
            [("[INFO] ", C_BLUE), ("Initializing SDR RTL2832U Pipeline on USB bus 001:004...", C_TEXT_WHITE)],
            [("  Device: ", C_TEXT_DIM), ("rtlsdr", C_CYAN), (" | Sample Rate: ", C_TEXT_DIM), ("2.048 MS/s", C_YELLOW), (" | Center Freq: ", C_TEXT_DIM), ("433.920 MHz", C_PURPLE)],
            [("  Gain: ", C_TEXT_DIM), ("30.0 dB", C_YELLOW), (" | Intermediate Filter: ", C_TEXT_DIM), ("Bandpass 125 kHz", C_GREEN), (" | Output: ", C_TEXT_DIM), ("output/frame.bin", C_TEXT_WHITE)],
            [("  LoRa Transceiver: ", C_TEXT_DIM), ("Semtech SX1262", C_PURPLE), (" | Modulation: ", C_TEXT_DIM), ("SF7 / BW 125kHz / CR 4/5", C_CYAN)],
            [("", C_TEXT_WHITE)],
            [("[PACKET #0482] ", C_GREEN, True), ("128 bytes received | RSSI: -74 dBm | SNR: +11.8 dB | CRC: OK", C_TEXT_WHITE)],
            [("  Telemetry Frame Decoded (Google Protocol Buffers v3):", C_TEXT_DIM)],
            [("    Altitude (MSL)    : ", C_TEXT_DIM), ("14,280.4 m", C_YELLOW, True), (" (Apogee Predicted: 15,100 m)", C_TEXT_DIM)],
            [("    Velocity Vector   : ", C_TEXT_DIM), ("Mach 1.84", C_RED, True), (" (Vertical: +626.4 m/s | Horizontal: +42.1 m/s)", C_TEXT_WHITE)],
            [("    Acceleration      : ", C_TEXT_DIM), ("+4.82 G", C_YELLOW), (" (Max Q: 34.2 kPa passed cleanly)", C_TEXT_DIM)],
            [("    IMU Attitude      : ", C_TEXT_DIM), ("Pitch: +84.2° | Yaw: -1.4° | Roll Rate: 12.0 rad/s", C_CYAN)],
            [("    Barometric Press  : ", C_TEXT_DIM), ("13.82 kPa", C_PURPLE), (" | Ambient Temp: -48.2 °C", C_TEXT_WHITE)],
            [("    Pyro Recovery     : ", C_TEXT_DIM), ("[Drogue: ARMED | Main: ARMED | Separation: STANDBY]", C_GREEN)],
            [("    Avionics Power    : ", C_TEXT_DIM), ("LiPo Bus: 12.42 V (94%) | Draw: 1.84 A", C_TEXT_WHITE)],
            [("", C_TEXT_WHITE)],
            [("[HIL LINK] ", C_PURPLE), ("Hardware-in-the-loop synchronized | Uplink ping: 14 ms | Zero packet drop", C_GREEN)]
        ],
        "status_left": "STREAM: LIVE | FREQ: 433.92 MHz | LOSS: 0.00% | LATENCY: 14ms | BUFFER: OK",
        "status_right": "LoRa SX1262 • SDR RTLSDR • Linux x86_64"
    },

    "blitzar": {
        "title": "blitzar_cli — Relativistic N-Body & Astrodynamics Simulation Engine",
        "subtitle": "HPC Tree-PM & KIFMM Gravitational Solver",
        "badge": "● BENCHMARK PASS",
        "badge_color": C_GREEN,
        "dir": "~/Bureau/.blitzar-build",
        "cmd": "./blitzar_scaling_test --particles 262144 --steps 10 --solver treepm",
        "lines": [
            [("[INIT] ", C_BLUE), ("BLITZAR SCALE schema=2 rank=0 ranks=1 particles=262144 seed=424242", C_TEXT_WHITE)],
            [("  Distribution: ", C_TEXT_DIM), ("Plummer sphere virial equilibrium", C_CYAN), (" | Solver: ", C_TEXT_DIM), ("Tree-PM + Octree FMM", C_PURPLE)],
            [("  Grid Layout : ", C_TEXT_DIM), ("256x256x256 FFT Mesh", C_YELLOW), (" | Multipole expansion order p=4", C_TEXT_WHITE)],
            [("", C_TEXT_WHITE)],
            [("[WARMUP] ", C_TEXT_DIM), ("Step 1/1: elapsed=32.4ms | throughput=", C_TEXT_WHITE), ("8,090,864 particles/sec", C_GREEN)],
            [("[TIMED]  ", C_GREEN), ("Step 01/10: dt=0.0010 | energy_drift=1.42e-7 | mean_step_ns=31450210", C_TEXT_WHITE)],
            [("[TIMED]  ", C_GREEN), ("Step 03/10: dt=0.0010 | energy_drift=2.10e-7 | leaf_particles_avg=14.2", C_TEXT_WHITE)],
            [("[TIMED]  ", C_GREEN), ("Step 05/10: dt=0.0010 | conservation: ΔE/E0 < 2.1e-6 | ΔL/L0 < 8.3e-8", C_CYAN)],
            [("[TIMED]  ", C_GREEN), ("Step 08/10: dt=0.0010 | Octree depth=14 levels | cell_interactions=1.84M", C_TEXT_WHITE)],
            [("[TIMED]  ", C_GREEN), ("Step 10/10: elapsed_total=318.2ms | peak_rss_bytes=44,890,112", C_TEXT_WHITE)],
            [("", C_TEXT_WHITE)],
            [("Throughput         : ", C_TEXT_DIM), ("8,238,410 particles/second", C_YELLOW, True), (" (Vectorized AVX-512)", C_TEXT_DIM)],
            [("Gravitational Error: ", C_TEXT_DIM), ("Max relative force error: 1.14e-6 (Analytical reference match)", C_GREEN)],
            [("Memory Footprint   : ", C_TEXT_DIM), ("Peak RSS: 42.8 MB | Bounded allocation contract: ZERO leaks", C_TEXT_WHITE)],
            [("STATUS             : ", C_GREEN, True), ("CONVERGED (All 10 integration steps completed within tolerances)", C_GREEN)]
        ],
        "status_left": "N=262,144 | O(N log N) TREE-PM | AVX-512 | RELATIVE ERR: 1.14e-6 | RSS: 42.8MB",
        "status_right": "HPC C++20 • OpenMP • KIFMM"
    },

    "pyrocast": {
        "title": "firemap_cli — Tactical Wildfire Spread & 3D CFD Atmospheric Engine",
        "subtitle": "Neural Fast Marching Method & Thermal Fluid Dynamics",
        "badge": "● SIMULATION FINISHED",
        "badge_color": C_ORANGE,
        "dir": "~/Bureau/GitHub/FireMap",
        "cmd": "python3 firemap_cli.py --lat 43.52 --lon 5.44 --wind-speed 35 --wind-dir NW --fuel pine --steps 12 --firebreak",
        "lines": [
            [("[*] ", C_ORANGE), ("FIREMAP TACTICAL CLI - MOTEUR NEURAL FMM / 3D CFD", C_TEXT_WHITE, True)],
            [("[*] Coordonnees Ignition : ", C_TEXT_DIM), ("Lat 43.5200° N, Lon 5.4400° E", C_CYAN), (" | Altitude: 420m (DEM Copernicus)", C_TEXT_DIM)],
            [("[*] Conditions Meteo     : ", C_TEXT_DIM), ("Vent NW (35.0 km/h) | Humidite: 18% | Temp: 38.5°C", C_YELLOW)],
            [("[*] Modele Combustible   : ", C_TEXT_DIM), ("PINE (Forêt dense de résineux, sécheresse 88/100)", C_RED)],
            [("[*] Tactique Defensif    : ", C_TEXT_DIM), ("Tranchée coupe-feu déployée (Largeur 50m, axe SW-NE)", C_GREEN)],
            [("", C_TEXT_WHITE)],
            [("[STEP 03/12] ", C_YELLOW), ("t+45 min : Rayon front 420m | Vitesse tête 9.2 m/min | Flux 14.8 MW/m", C_TEXT_WHITE)],
            [("[STEP 06/12] ", C_YELLOW), ("t+90 min : Effet de pente +18° détecté | Accélération flanc gauche", C_TEXT_WHITE)],
            [("[STEP 09/12] ", C_YELLOW), ("t+135min : Contact avec la tranchée coupe-feu tactique à l'azimut 135°", C_CYAN)],
            [("             ", C_TEXT_DIM), ("-> Flammes bloquées sur le front principal (Efficacité: 87.4%)", C_GREEN)],
            [("[STEP 12/12] ", C_GREEN), ("t+180min : Stabilisation du périmètre incendie", C_GREEN, True)],
            [("", C_TEXT_WHITE)],
            [("BILAN SIMULATION : ", C_TEXT_WHITE, True), ("Surface finale brûlée: ", C_TEXT_DIM), ("142.6 ha", C_ORANGE, True), (" (Scénario sans barrière: 318.4 ha)", C_TEXT_DIM)],
            [("ECONOMIE FORESTIERE: ", C_TEXT_WHITE, True), ("175.8 ha épargnés grâce au positionnement coupe-feu optimal", C_GREEN)],
            [("[EXPORT] ", C_BLUE), ("Périmètre WGS84 exporté -> outputs/fire_perimeter_t180.geojson (PASS)", C_TEXT_WHITE)]
        ],
        "status_left": "GRID: 512x512 | CELL: 10m | FMM NEURAL | SURFACE: 142.6ha | EXPORT: GeoJSON OK",
        "status_right": "Python 3.12 • NumPy • PyTorch"
    },

    "antman-compression": {
        "title": "antman — Dynamic Huffman & Dictionary Data Compression Engine",
        "subtitle": "Dual-Pass Canonical Huffman & Bitstream Serializer",
        "badge": "● RATIO: 64.8%",
        "badge_color": C_GREEN,
        "dir": "~/antman-compression",
        "cmd": "./antman/antman corpus/large_text.txt 1 > compressed.bin && ./giantman/giantman compressed.bin 1 | diff -s corpus/large_text.txt -",
        "lines": [
            [("[ANTMAN] ", C_BLUE), ("Analyzing input stream: corpus/large_text.txt (68,420 bytes)", C_TEXT_WHITE)],
            [("  Building frequency histogram... ", C_TEXT_DIM), ("86 distinct ASCII byte symbols", C_CYAN)],
            [("  Constructing Canonical Huffman Tree... ", C_TEXT_DIM), ("Max tree depth = 11 bits", C_YELLOW)],
            [("  Serializing dictionary header... ", C_TEXT_DIM), ("198 bytes overhead", C_PURPLE)],
            [("  Packing variable-length bitstream...", C_TEXT_DIM)],
            [("    Original payload size : ", C_TEXT_DIM), ("68,420 bytes", C_TEXT_WHITE)],
            [("    Compressed payload size: ", C_TEXT_DIM), ("44,336 bytes", C_GREEN, True)],
            [("    Compression ratio      : ", C_TEXT_DIM), ("64.8%", C_GREEN, True), (" (Storage savings: ", C_TEXT_DIM), ("35.2% / 24,084 bytes", C_YELLOW), (")", C_TEXT_DIM)],
            [("", C_TEXT_WHITE)],
            [("[GIANTMAN] ", C_PURPLE), ("Decompressing bitstream: compressed.bin", C_TEXT_WHITE)],
            [("  Reading serialized frequency table... [OK]", C_TEXT_DIM)],
            [("  Reconstructing prefix tree... [OK]", C_TEXT_DIM)],
            [("  Traversing bitstream: 68,420 bytes restored in 0.8ms", C_TEXT_WHITE)],
            [("", C_TEXT_WHITE)],
            [("[INTEGRITY] ", C_GREEN, True), ("Files corpus/large_text.txt and - are identical.", C_GREEN, True)],
            [("Verification: Bit-for-bit lossless roundtrip MD5 match: PASS", C_TEXT_DIM)]
        ],
        "status_left": "IN: 68.4 KB | OUT: 44.3 KB | RATIO: 64.8% | SPEED: 85 MB/s | LOSSLESS: 100%",
        "status_right": "C Systems • Huffman Coding • Bitwise I/O"
    },

    "bistromatic": {
        "title": "bistromatic — Arbitrary-Precision Infinite Calculator",
        "subtitle": "Arbitrary Base Large Number Shunting-Yard Evaluator",
        "badge": "● EXACT PRECISION",
        "badge_color": C_CYAN,
        "dir": "~/bistromatic",
        "cmd": "echo '99999999999999999999999999999999999999999999999999*2' | ./calc '0123456789' '()+-*/%' 53",
        "lines": [
            [("[BISTROMATIC ENGINE] ", C_CYAN), ("Initializing arbitrary base big-integer parser", C_TEXT_WHITE)],
            [("  Base charset: ", C_TEXT_DIM), ("0123456789 (Base 10)", C_TEXT_WHITE), (" | Operator set: ", C_TEXT_DIM), ("()+-*/%", C_YELLOW)],
            [("  Expression length: ", C_TEXT_DIM), ("53 bytes", C_PURPLE), (" | Syntax validation: PASS", C_GREEN)],
            [("", C_TEXT_WHITE)],
            [("Operand A (50 decimal digits):", C_TEXT_DIM)],
            [("  99999999999999999999999999999999999999999999999999", C_YELLOW)],
            [("Operator: MULTIPLICATION (*)", C_TEXT_DIM)],
            [("Operand B (1 decimal digit) :", C_TEXT_DIM)],
            [("  2", C_YELLOW)],
            [("Calculation Algorithm: Karatsuba BigInt digit convolution with carry propagation", C_TEXT_DIM)],
            [("", C_TEXT_WHITE)],
            [("Exact Result (51 decimal digits):", C_TEXT_WHITE, True)],
            [("  199999999999999999999999999999999999999999999999998", C_GREEN, True)],
            [("", C_TEXT_WHITE)],
            [("[STRESS BENCHMARK] ", C_PURPLE), ("10^1000 / 7 evaluated to 1,000 decimal places in 0.42 ms: PASS", C_TEXT_WHITE)]
        ],
        "status_left": "PRECISION: UNLIMITED | DIGITS: 51 | TIME: 0.04ms | ALLOC: HEAP BIGINT | STATUS: OK",
        "status_right": "Pure C • BigInt Arithmetic • AST Parser"
    },

    "bsq": {
        "title": "bsq — Maximal Square Dynamic Programming Finder",
        "subtitle": "O(N*M) Linear-Time Obstacle Grid Solver",
        "badge": "● DP SOLVER 0.8ms",
        "badge_color": C_GREEN,
        "dir": "~/bsq",
        "cmd": "./bsq maps/grid_obstacle_15x15.map",
        "lines": [
            [("[BSQ ENGINE] ", C_BLUE), ("Reading grid map: maps/grid_obstacle_15x15.map (15 rows)", C_TEXT_WHITE)],
            [("  Grid Dimensions: ", C_TEXT_DIM), ("15 x 15 (225 cells)", C_CYAN), (" | Obstacle Density: ", C_TEXT_DIM), ("4.8%", C_YELLOW)],
            [("  Legend: Empty='.' | Obstacle='o' | Maximal Square='x'", C_TEXT_DIM)],
            [("  Dynamic Programming recurrence: DP[i][j] = 1 + min(DP[i-1][j], DP[i][j-1], DP[i-1][j-1])", C_PURPLE)],
            [("", C_TEXT_WHITE)],
            [("  ..o.xxxxxx.....", C_TEXT_WHITE)],
            [("  ....xxxxxx.o...", C_TEXT_WHITE)],
            [("  ....xxxxxx.....", C_GREEN, True)],
            [("  ....xxxxxx.....", C_GREEN, True)],
            [("  ..o.xxxxxx.....", C_GREEN, True)],
            [("  ....xxxxxx.....", C_GREEN, True)],
            [("  .......o.......", C_TEXT_WHITE)],
            [("  ...o...........", C_TEXT_WHITE)],
            [("  .........o.o...", C_TEXT_WHITE)],
            [("  ...............", C_TEXT_WHITE)],
            [("", C_TEXT_WHITE)],
            [("[SOLVED] ", C_GREEN, True), ("Maximal square size: ", C_TEXT_WHITE), ("6 x 6", C_YELLOW, True), (" at top-left origin (x=4, y=0)", C_TEXT_WHITE)],
            [("Complexity: Single-pass O(N) memory & execution | Time: 0.82 ms | Memory: 48 KB", C_TEXT_DIM)]
        ],
        "status_left": "MAP: 15x15 | SQUARE: 6x6 | COMPLEXITY: O(N*M) | CPU: 0.82ms | MEM: 48KB",
        "status_right": "Dynamic Programming • C Primitives"
    },

    "cryptography": {
        "title": "cryptography — RSA Asymmetric & Symmetric Cipher Suite",
        "subtitle": "Modular Exponentiation & Miller-Rabin Prime Generation",
        "badge": "● 2048-BIT RSA PASS",
        "badge_color": C_PURPLE,
        "dir": "~/cryptography",
        "cmd": "./crypto_suite --rsa-gen 2048 --encrypt 'CONFIDENTIAL_PAYLOAD_X86'",
        "lines": [
            [("[RSA KEYGEN] ", C_PURPLE), ("Generating 2048-bit prime pairs via Miller-Rabin test (k=64)", C_TEXT_WHITE)],
            [("  Prime P (1024-bit): ", C_TEXT_DIM), ("0xd3a4...8f1a", C_YELLOW), (" (Verified prime in 14 iterations)", C_TEXT_DIM)],
            [("  Prime Q (1024-bit): ", C_TEXT_DIM), ("0xe8b1...9c32", C_YELLOW), (" (Verified prime in 18 iterations)", C_TEXT_DIM)],
            [("  Modulus N = P * Q : ", C_TEXT_DIM), ("2048 bits computed", C_CYAN), (" | Euler Totient φ(N) derived", C_TEXT_DIM)],
            [("  Public Exponent E : ", C_TEXT_DIM), ("65537 (0x10001)", C_GREEN), (" | Private D via Extended Euclidean: OK", C_TEXT_DIM)],
            [("", C_TEXT_WHITE)],
            [("[ENCRYPTION] ", C_BLUE), ("Ciphertext C = M^e mod N (Modular Montgomery Exponentiation)", C_TEXT_WHITE)],
            [("  Plaintext Input   : ", C_TEXT_DIM), ("\"CONFIDENTIAL_PAYLOAD_X86\" (24 bytes)", C_TEXT_WHITE)],
            [("  Ciphertext Output : ", C_TEXT_DIM), ("7a9f82d1c045b8e3a201f8d3...44f9e1b8 (256 bytes)", C_YELLOW)],
            [("", C_TEXT_WHITE)],
            [("[DECRYPTION] ", C_GREEN), ("Plaintext M = C^d mod N (Chinese Remainder Theorem accelerated)", C_TEXT_WHITE)],
            [("  CRT Speedup Factor: ", C_TEXT_DIM), ("3.82x vs naive modular exponentiation", C_GREEN)],
            [("  Decrypted Payload : ", C_TEXT_DIM), ("\"CONFIDENTIAL_PAYLOAD_X86\"", C_GREEN, True), (" [100% MATCH]", C_GREEN)],
            [("", C_TEXT_WHITE)],
            [("Security Gate: Constant-time Montgomery ladder immune to timing side-channels.", C_TEXT_DIM)]
        ],
        "status_left": "RSA: 2048-BIT | PRIMALITY: MILLER-RABIN | CRT: ACCELERATED | SIDE-CHANNEL: SAFE",
        "status_right": "Modular Arithmetic • Cryptography"
    },

    "dante-star": {
        "title": "dante-star — Procedural Maze Generator & A* Pathfinder",
        "subtitle": "Recursive Backtracking & Heuristic Pathfinding",
        "badge": "● A* SOLVER PASS",
        "badge_color": C_GREEN,
        "dir": "~/dante-star",
        "cmd": "./generator/generator 15 10 > maze.txt && ./solver/solver maze.txt",
        "lines": [
            [("[GENERATOR] ", C_BLUE), ("Generating 15x10 imperfect maze with recursive backtracker...", C_TEXT_WHITE)],
            [("  Dead-ends pruned, cycle loops inserted for realistic path ambiguity.", C_TEXT_DIM)],
            [("", C_TEXT_WHITE)],
            [("  XXXXXXXXXXXXXXX", C_TEXT_MUTED)],
            [("  Xooooo*X*****X*", C_GREEN, True)],
            [("  X*X**ooo****X*X", C_GREEN, True)],
            [("  X*****Xoooo***X", C_GREEN, True)],
            [("  X*X***X*X*ooo*X", C_GREEN, True)],
            [("  X*****X***X*o*X", C_GREEN, True)],
            [("  X*X***X*****ooo", C_GREEN, True)],
            [("  XXXXXXXXXXXXXXX", C_TEXT_MUTED)],
            [("", C_TEXT_WHITE)],
            [("[A* SOLVER] ", C_GREEN), ("Heuristic: Manhattan Distance | OpenSet Priority Queue: Binary Heap", C_TEXT_WHITE)],
            [("  Nodes explored: 48/150 (32.0%) | Optimal path length: 22 steps", C_CYAN)],
            [("  Start: (1, 1) -> Exit: (14, 8) | Status: ", C_TEXT_DIM), ("SOLVED (Marked with 'o')", C_GREEN, True)],
            [("Execution time: 0.38 ms | Memory allocated: 12 KB | Zero memory leak", C_TEXT_DIM)]
        ],
        "status_left": "GRID: 15x10 | PATH: 22 STEPS | EXPLORED: 48 NODES | HEURISTIC: MANHATTAN | PASS",
        "status_right": "A* Pathfinding • Procedural Generation"
    },

    "evalexpr": {
        "title": "evalexpr — Arithmetic Expression AST Evaluator",
        "subtitle": "Shunting-Yard Parser & Operator Precedence Engine",
        "badge": "● PARSER PASS",
        "badge_color": C_CYAN,
        "dir": "~/evalexpr",
        "cmd": "./eval_expr \"(12 + 4 * (8 - 3)) / 2 + 10 % 3\"",
        "lines": [
            [("[INPUT EXPRESSION] ", C_CYAN), ("\"(12 + 4 * (8 - 3)) / 2 + 10 % 3\"", C_YELLOW, True)],
            [("[LEXICAL TOKENS]  ", C_TEXT_DIM), ("['(', '12', '+', '4', '*', '(', '8', '-', '3', ')', ')', '/', '2', '+', '10', '%', '3']", C_TEXT_WHITE)],
            [("[SHUNTING-YARD]   ", C_PURPLE), ("Postfix (RPN): 12 4 8 3 - * + 2 / 10 3 % +", C_TEXT_WHITE)],
            [("", C_TEXT_WHITE)],
            [("Abstract Syntax Tree (AST):", C_TEXT_DIM)],
            [("          +              Evaluation Step 1: (8 - 3) = 5", C_TEXT_WHITE)],
            [("         / \\             Evaluation Step 2: (4 * 5) = 20", C_TEXT_WHITE)],
            [("        /   %            Evaluation Step 3: (12 + 20) = 32", C_TEXT_WHITE)],
            [("       /   / \\           Evaluation Step 4: (32 / 2) = 16", C_TEXT_WHITE)],
            [("      +   10  3          Evaluation Step 5: (10 % 3) = 1", C_TEXT_WHITE)],
            [("     / \\                 Evaluation Step 6: (16 + 1) = 17", C_TEXT_WHITE)],
            [("    12  *                ", C_TEXT_WHITE)],
            [("       / \\               ", C_TEXT_WHITE)],
            [("      4   -              ", C_TEXT_WHITE)],
            [("", C_TEXT_WHITE)],
            [("[EVALUATION RESULT] ", C_GREEN, True), ("17", C_YELLOW, True), (" (Computed in 0.01 ms)", C_TEXT_DIM)]
        ],
        "status_left": "TOKENS: 17 | POSTFIX: RPN | AST: BALANCED | PRECEDENCE: PEMDAS | EXIT: 0",
        "status_right": "Shunting-Yard • Compiler AST • C99"
    },

    "fastatools": {
        "title": "fastatools — Bioinformatics Sequence Analysis Engine",
        "subtitle": "DNA/RNA Processing, K-Mers & Amino Acid Translation",
        "badge": "● GENOME ANALYZER",
        "badge_color": C_GREEN,
        "dir": "~/fastatools",
        "cmd": "./FASTAtools 2 < beta_globin.fasta && ./FASTAtools 3 < beta_globin.fasta",
        "lines": [
            [("[OPTION 2] RNA Transcription (Thymine -> Uracil substitution):", C_BLUE)],
            [("  >seq1 Human beta-globin mRNA transcript (180 nucleotides)", C_TEXT_DIM)],
            [("  AUGGUGCACCUGACUCCUGAGGAGAAGUCUGCCGUUACUGCCCUGUGGGGCAAGGUGAACGUGGAUGAAGUUGGUGGUG", C_GREEN)],
            [("  AGGCCCUGGGCAGGCUGCUGGUGGUCUACCCUUGGACCCAGAGGUUCUUUGAGUCCUUUGGGGAUCUGUCCACUCCUGA", C_GREEN)],
            [("  UGCUGUUAUGGGCAACCCUAAG", C_GREEN)],
            [("", C_TEXT_WHITE)],
            [("[OPTION 3] Reverse Complement (3' -> 5' Watson-Crick antiparallel):", C_PURPLE)],
            [("  >seq1 Human beta-globin Reverse Complement", C_TEXT_DIM)],
            [("  CTTAGGGTTGCCCATAACAGCATCAGGAGTGGACAGATCCCCAAAGGACTCAAAGAACCTCTGGGTCCAAGGGTAGACC", C_YELLOW)],
            [("  ACCAGCAGCCTGCCCAGGGCCTCACCACCAACTTCATCCACGTTCACCTTGCCCCACAGGGCAGTAACGGCAGACTTCT", C_YELLOW)],
            [("  CCTCAGGAGTCAGGTGCACCAT", C_YELLOW)],
            [("", C_TEXT_WHITE)],
            [("[SEQUENCE METRICS] ", C_TEXT_WHITE, True)],
            [("  Length: 180 bp | GC-Content: 58.33% (G: 52, C: 53, A: 38, T: 37)", C_CYAN)],
            [("  Open Reading Frames (ORF): 1 continuous coding frame detected (Met -> Stop)", C_TEXT_WHITE)],
            [("  K-mer spectrum analysis (k=6): 142 distinct motifs indexed in hash table", C_TEXT_DIM)]
        ],
        "status_left": "FASTA: WGS84 | GC: 58.33% | RNA: ACTIVE | K-MERS: HASHED | PIPELINE: PASS",
        "status_right": "Bioinformatics • Sequence Alignment • C"
    },

    "gomoku-ai": {
        "title": "gomoku-ai — Minimax Alpha-Beta Gomoku AI Engine",
        "subtitle": "Zobrist Hashing, Bitboards & Threat Space Search",
        "badge": "● DEPTH 8 SEARCH",
        "badge_color": C_CYAN,
        "dir": "~/gomoku-ai",
        "cmd": "./pbrain-gomoku-ai",
        "lines": [
            [("[GOMOCUP PROTOCOL] ", C_BLUE), ("START 20 (Board initialized: 20x20 bitboard array)", C_TEXT_WHITE)],
            [("OK", C_GREEN)],
            [("TURN 10,10 (Opponent played center stone at coordinates 10,10)", C_TEXT_WHITE)],
            [("[SEARCH ENGINE] ", C_PURPLE), ("Iterative Deepening Search active (Time limit: 500ms):", C_TEXT_WHITE)],
            [("  Depth 2: Nodes:    420 | Best: (10, 11) | Eval: +45", C_TEXT_DIM)],
            [("  Depth 4: Nodes:  8,910 | Best: (10, 11) | Eval: +120", C_TEXT_DIM)],
            [("  Depth 6: Nodes: 64,200 | Best: (10, 11) | Eval: +340 (Alpha cutoffs: 84.2%)", C_TEXT_DIM)],
            [("  Depth 8: Nodes: 248,100 | Best: (10, 11) | Eval: +680 (Threat sequence confirmed)", C_CYAN)],
            [(">> Response emitted: ", C_TEXT_DIM), ("10,11", C_YELLOW, True), (" (Elapsed: 184 ms)", C_TEXT_DIM)],
            [("", C_TEXT_WHITE)],
            [("BOARD", C_TEXT_DIM)],
            [("10,10,2", C_TEXT_DIM), ("   (Opponent stone)", C_TEXT_MUTED)],
            [("10,11,1", C_TEXT_DIM), ("   (AI stone)", C_TEXT_MUTED)],
            [("9,10,2", C_TEXT_DIM), ("    (Opponent stone)", C_TEXT_MUTED)],
            [("DONE", C_TEXT_DIM)],
            [("[THREAT EVALUATION] ", C_GREEN), ("Open-three pattern established | Win probability: 82.4%", C_GREEN)]
        ],
        "status_left": "BOARD: 20x20 | DEPTH: 8 | NODES: 248K | ZOBRIST HIT: 72% | RESPONSE: 184ms",
        "status_right": "Minimax • Alpha-Beta • Gomocup AI"
    },

    "infinadd": {
        "title": "infinadd — Arbitrary-Precision Large Integer Addition",
        "subtitle": "Pure C Infinite Carry Propagation Engine",
        "badge": "● O(N) LINEAR TIME",
        "badge_color": C_GREEN,
        "dir": "~/infinadd",
        "cmd": "./infin_add '987654321098765432109876543210' '123456789012345678901234567890'",
        "lines": [
            [("[INFINADD ENGINE] ", C_BLUE), ("Reading arbitrary-length integer operands from argv", C_TEXT_WHITE)],
            [("  Operand A length: 30 digits | Sign: POSITIVE", C_TEXT_DIM)],
            [("  Operand B length: 30 digits | Sign: POSITIVE", C_TEXT_DIM)],
            [("", C_TEXT_WHITE)],
            [("    987654321098765432109876543210", C_YELLOW)],
            [("  + 123456789012345678901234567890", C_YELLOW)],
            [("  --------------------------------", C_TEXT_MUTED)],
            [("    1111111110111111111011111111100", C_GREEN, True)],
            [("", C_TEXT_WHITE)],
            [("[EXECUTION METRICS] ", C_TEXT_WHITE, True)],
            [("  Memory allocated : ", C_TEXT_DIM), ("32 bytes (1 byte per ASCII digit + NUL terminator)", C_CYAN)],
            [("  Carry iterations : ", C_TEXT_DIM), ("30 consecutive carry ripple additions", C_TEXT_WHITE)],
            [("  Execution time   : ", C_TEXT_DIM), ("0.02 ms (Benchmark verified against GMP)", C_GREEN)],
            [("  Negative operands: ", C_TEXT_DIM), ("Compliant with dual negative and subtraction carry rules", C_TEXT_WHITE)],
            [("Status: Complete precision maintained. Zero truncation.", C_TEXT_DIM)]
        ],
        "status_left": "DIGITS: 30 | CARRY: RIPPLE PROPAGATION | TIME: 0.02ms | MEM: 32B | PASS",
        "status_right": "BigInt Addition • C Primitives"
    },

    "lemin": {
        "title": "lemin — Graph Anthill Network Flow Routing Optimizer",
        "subtitle": "Edmonds-Karp / Dinic Maximum Disjoint Flow Paths",
        "badge": "● OPTIMAL 14 TURNS",
        "badge_color": C_YELLOW,
        "dir": "~/lemin",
        "cmd": "./lem_in < anthill_complex.map",
        "lines": [
            [("[ANTHILL TOPOLOGY] ", C_BLUE), ("Ants: 34 | Rooms: 12 | Tunnels: 24 | Source: ##start (1) | Sink: ##end (0)", C_TEXT_WHITE)],
            [("[FLOW OPTIMIZER]   ", C_PURPLE), ("Breadth-First Search on Residual Flow Network", C_TEXT_WHITE)],
            [("  Disjoint Path 1 (len 3): ", C_TEXT_DIM), ("1 -> 3 -> 4 -> 0", C_CYAN), (" (Capacity: 1 ant/turn)", C_TEXT_DIM)],
            [("  Disjoint Path 2 (len 4): ", C_TEXT_DIM), ("1 -> 2 -> 5 -> 6 -> 0", C_GREEN), (" (Capacity: 1 ant/turn)", C_TEXT_DIM)],
            [("  Disjoint Path 3 (len 5): ", C_TEXT_DIM), ("1 -> 7 -> 8 -> 9 -> 10 -> 0", C_YELLOW), (" (Capacity: 1 ant/turn)", C_TEXT_DIM)],
            [("", C_TEXT_WHITE)],
            [("SYNCHRONIZED TURN DISPATCH:", C_TEXT_WHITE, True)],
            [("  Turn 1 : P1-3 P2-2", C_TEXT_WHITE)],
            [("  Turn 2 : P1-4 P2-5 P3-3 P4-2", C_TEXT_WHITE)],
            [("  Turn 3 : P1-0 P2-6 P3-4 P4-5 P5-3 P6-2", C_GREEN)],
            [("  Turn 4 : P2-0 P3-0 P4-6 P5-4 P6-5 P7-3 P8-2", C_GREEN)],
            [("  Turn 5 : P4-0 P5-0 P6-6 P7-4 P8-5 P9-3 P10-2 P11-7", C_GREEN)],
            [("  ...", C_TEXT_MUTED)],
            [("  Turn 14: P34-0 (All ants successfully evacuated!)", C_YELLOW, True)],
            [("", C_TEXT_WHITE)],
            [("[VERDICT] ", C_GREEN, True), ("Theoretical minimum: 14 turns | Engine achieved: 14 turns (100% Optimal)", C_GREEN)]
        ],
        "status_left": "ANTS: 34 | PATHS: 3 DISJOINT | EDMONDS-KARP | TURNS: 14 (OPTIMAL) | EXIT: 0",
        "status_right": "Network Flow • Dinic Algorithm • Graph Theory"
    },

    "n4s-autonomous": {
        "title": "n4s-autonomous — Autonomous Vehicle LiDAR Controller",
        "subtitle": "CoppeliaSim Virtual Track PID Steering & Speed Governor",
        "badge": "● AUTONOMOUS PILOT",
        "badge_color": C_CYAN,
        "dir": "~/n4s-autonomous",
        "cmd": "./ai_controller",
        "lines": [
            [("[COPPELIASIM IPC] ", C_BLUE), ("Connected to track simulation engine (Pipe /dev/stdin)", C_TEXT_WHITE)],
            [("  Car State: ", C_TEXT_DIM), ("Speed: 0.85 (Max: 1.0) | Steering Angle: +0.04 rad | Gear: 3", C_TEXT_WHITE)],
            [("", C_TEXT_WHITE)],
            [("LiDAR 32-Ray Range Sweep (Frontal cone):", C_TEXT_DIM)],
            [("  Left rays   [00-05]: ", C_TEXT_DIM), ("[ 2.4m,  3.1m,  4.8m,  6.2m,  8.1m ]", C_YELLOW)],
            [("  Center rays [14-17]: ", C_TEXT_DIM), ("[ 18.4m, 19.2m, 19.1m, 18.0m ]", C_GREEN, True)],
            [("  Right rays  [26-31]: ", C_TEXT_DIM), ("[ 1.2m,  1.4m,  1.8m,  2.5m,  3.0m ]", C_RED)],
            [("", C_TEXT_WHITE)],
            [("[PID CONTROLLER STATE] ", C_PURPLE)],
            [("  Lateral Trajectory Error: ", C_TEXT_DIM), ("-0.62m (Approaching right apex curb)", C_YELLOW)],
            [("  Proportional Term (Kp=0.8) : -0.18 rad", C_TEXT_DIM)],
            [("  Derivative Term   (Kd=0.3) : -0.04 rad (Damping oscillation)", C_TEXT_DIM)],
            [("  Integral Term     (Ki=0.01):  0.00 rad", C_TEXT_DIM)],
            [("  Output Command    : ", C_TEXT_DIM), ("WHEELS_DIR:-0.22 | CAR_FORWARD:0.72", C_CYAN, True)],
            [("", C_TEXT_WHITE)],
            [("[LAP TELEMETRY] ", C_GREEN, True), ("Lap 1/3: Checkpoint 4/8 passed cleanly [Zero collision, 14.8s split]", C_GREEN)]
        ],
        "status_left": "LiDAR: 32 RAYS | SPEED: 85% | STEER: -0.22 rad | PID: CONVERGED | ZERO CRASH",
        "status_right": "Robotics • PID Control • Autonomous Vehicles"
    },

    "neural-network": {
        "title": "neural-network — Feedforward Neural Network Engine",
        "subtitle": "FEN Chessboard State Evaluator & Weight Optimizer",
        "badge": "● INFERENCE ACTIVE",
        "badge_color": C_PURPLE,
        "dir": "~/neural-network",
        "cmd": "./my_torch_analyzer --predict 'weights.json' < chessboard.txt",
        "lines": [
            [("[NEURAL TOPOLOGY] ", C_PURPLE), ("Multi-Layer Perceptron (MLP) Architecture:", C_TEXT_WHITE)],
            [("  Input Layer   : ", C_TEXT_DIM), ("64 neurons (One-hot piece encoding per board square)", C_CYAN)],
            [("  Hidden Layer 1: ", C_TEXT_DIM), ("128 neurons (ReLU activation, L2 regularization λ=0.001)", C_TEXT_WHITE)],
            [("  Hidden Layer 2: ", C_TEXT_DIM), ("64 neurons (ReLU activation)", C_TEXT_WHITE)],
            [("  Output Layer  : ", C_TEXT_DIM), ("1 neuron (Tanh activation, Evaluation score [-1.0, +1.0])", C_YELLOW)],
            [("", C_TEXT_WHITE)],
            [("[INPUT FEN] ", C_BLUE), ("\"r1bqk2r/pp2bppp/2n1pn2/2pp4/2PP4/2N1PN2/PP2BPPP/R1BQK2R w KQkq - 0 1\"", C_TEXT_WHITE)],
            [("Forward Propagation Matrix Operations (SIMD AVX2):", C_TEXT_DIM)],
            [("  Layer 1 Dense Dot Product: 64x128 weights + bias -> Activation: ReLU", C_TEXT_DIM)],
            [("  Layer 2 Dense Dot Product: 128x64 weights + bias -> Activation: ReLU", C_TEXT_DIM)],
            [("  Output Layer Dot Product : 64x1 weights + bias  -> Activation: Tanh", C_TEXT_DIM)],
            [("", C_TEXT_WHITE)],
            [("[PREDICTION RESULT] ", C_GREEN, True)],
            [("  Position Evaluation: ", C_TEXT_DIM), ("+0.34", C_GREEN, True), (" (White territorial space advantage)", C_TEXT_DIM)],
            [("  Engine Confidence  : ", C_TEXT_DIM), ("91.2%", C_CYAN), (" | Mean Squared Error (MSE): 0.042", C_TEXT_DIM)],
            [("Inference Latency: 0.42 ms per position | Throughput: 2,380 boards/sec", C_TEXT_DIM)]
        ],
        "status_left": "MLP: 64-128-64-1 | ACTIVATION: RELU/TANH | LATENCY: 0.42ms | ACCURACY: 91.2%",
        "status_right": "Deep Learning • Neural Networks • NumPy"
    },

    "pushswap": {
        "title": "pushswap — Two-Stack Sorting Algorithm Optimizer",
        "subtitle": "Minimal Operation Sequence Radix & Quick Sort",
        "badge": "● 100% SORTED [PASS]",
        "badge_color": C_GREEN,
        "dir": "~/pushswap",
        "cmd": "./push_swap 25 12 89 3 45 78 1 90 34 56",
        "lines": [
            [("[INITIAL STATE] ", C_BLUE), ("Stack A: [25, 12, 89, 3, 45, 78, 1, 90, 34, 56] (10 values)", C_TEXT_WHITE)],
            [("                 Stack B: [] (Empty)", C_TEXT_DIM)],
            [("", C_TEXT_WHITE)],
            [("Computing optimal operation sequence via dual-pivot partition:", C_TEXT_DIM)],
            [("  rra rra rra rra pb rra rra rra pb rra rra pb rra pb rra rra pb", C_YELLOW)],
            [("  ra ra pb ra ra pb ra pb ra pb pb pa pa pa pa pa pa pa pa pa pa", C_YELLOW)],
            [("", C_TEXT_WHITE)],
            [("[RESULTING STACK A] ", C_GREEN, True)],
            [("  [1, 3, 12, 25, 34, 45, 56, 78, 89, 90]", C_GREEN, True), (" (Sorted ascending)", C_TEXT_DIM)],
            [("[RESULTING STACK B] ", C_TEXT_DIM), ("[] (Cleanly emptied)", C_TEXT_DIM)],
            [("", C_TEXT_WHITE)],
            [("[PERFORMANCE BENCHMARK] ", C_TEXT_WHITE, True)],
            [("  Operations emitted : ", C_TEXT_DIM), ("32 ops", C_CYAN, True), (" (Max allowed limit for 10 elements: 700)", C_TEXT_DIM)],
            [("  100-element suite  : Average 640 operations (Target < 700) -> Grade: 100%", C_GREEN)],
            [("  500-element suite  : Average 4,820 operations (Target < 5500) -> Grade: 100%", C_GREEN)],
            [("Memory validation: Zero malloc leakage, strict O(1) auxiliary space.", C_TEXT_DIM)]
        ],
        "status_left": "N=10 | OPS: 32 | CHECKER: OK | MEMORY: CLEAN | RATING: MAX SCORE",
        "status_right": "Stack Algorithms • Two-Pointer Sorting • C"
    },

    "sokoban": {
        "title": "sokoban — Ncurses Terminal Warehouse Box-Pushing Engine",
        "subtitle": "Terminal Grid Matrix & Collision Detection Engine",
        "badge": "● 60 FPS NCURSES",
        "badge_color": C_YELLOW,
        "dir": "~/sokoban",
        "cmd": "./my_sokoban maps/level_04.map",
        "lines": [
            [("############  ", C_TEXT_MUTED), ("[SOKOBAN TERMINAL ENGINE]", C_YELLOW, True)],
            [("#   #      #  ", C_TEXT_MUTED), ("Player Position : ", C_TEXT_DIM), ("(x=3, y=2) '@'", C_CYAN)],
            [("# @ $  .   #  ", C_TEXT_WHITE), ("Boxes Remaining : ", C_TEXT_DIM), ("2/3 on target", C_YELLOW)],
            [("#  ###$    #  ", C_TEXT_WHITE), ("Total Move Count: ", C_TEXT_DIM), ("24 steps | Pushes: 9", C_TEXT_WHITE)],
            [("#  #   $   #  ", C_TEXT_WHITE), ("Game Status     : ", C_TEXT_DIM), ("PLAYING (Arrow keys to move)", C_GREEN)],
            [("#  #  .    #  ", C_TEXT_WHITE)],
            [("#  #       #  ", C_TEXT_WHITE), ("[DEADLOCK VALIDATOR]", C_PURPLE)],
            [("#  #   .   #  ", C_TEXT_WHITE), ("  Corner traps check   : 0 deadlocked boxes", C_GREEN)],
            [("############  ", C_TEXT_MUTED), ("  Wall-line traps check: Pass", C_GREEN)],
            [("", C_TEXT_WHITE)],
            [("Key Handlers: KEY_UP, KEY_DOWN, KEY_LEFT, KEY_RIGHT, SPACE (Reset)", C_TEXT_DIM)],
            [("Signal handler: SIGWINCH terminal resize detection active.", C_TEXT_DIM)],
            [("Exit criteria: Win (all boxes on targets '.') or Lose (stuck box).", C_TEXT_DIM)]
        ],
        "status_left": "GRID: 12x10 | BOXES: 3 | STATUS: ACTIVE | REFRESH: NCURSES RAW | LEVEL: 04",
        "status_right": "Ncurses TUI • Game Engine • C"
    },

    "trade": {
        "title": "trade — Algorithmic Cryptocurrency Trading Bot",
        "subtitle": "NumPy LSTM Neural Network & Technical Indicators",
        "badge": "● PROFIT: +24.8%",
        "badge_color": C_GREEN,
        "dir": "~/trade",
        "cmd": "./trade < market_candlesticks_stream.log",
        "lines": [
            [("[LSTM BOT INITIALIZED] ", C_BLUE), ("Loaded model weights from parameters/model_*.npy", C_TEXT_WHITE)],
            [("  Exchange Fee: 0.002% | Assets: USDT (Base) / BTC (Crypto)", C_TEXT_DIM)],
            [("  Current Portfolio: USDT: 1,420.50 | BTC: 0.185 | Total: ", C_TEXT_DIM), ("$12,480.00", C_GREEN, True)],
            [("", C_TEXT_WHITE)],
            [("Processing Candlestick #0412 (15m interval):", C_TEXT_DIM)],
            [("  Open: $59,800 | High: $60,450 | Low: $59,720 | Close: $60,380 | Vol: 48.2 BTC", C_TEXT_WHITE)],
            [("  Technical Indicators:", C_TEXT_DIM)],
            [("    Exponential Moving Avg: EMA(12): 60,110.4 | EMA(26): 59,840.2", C_CYAN)],
            [("    MACD Indicator        : +270.2 (Bullish crossover confirmed)", C_GREEN)],
            [("    Bollinger Bands (2σ)  : Lower: $59,200 | Mid: $59,950 | Upper: $60,700", C_YELLOW)],
            [("  LSTM 3-Step Predictive Tensor Forecast: Target price +1.4% ($61,225)", C_PURPLE)],
            [("", C_TEXT_WHITE)],
            [("[ORDER EXECUTION] ", C_GREEN, True), ("BUY 0.015 BTC at $60,380.00 (Market Order)", C_GREEN, True)],
            [("  Transaction cost: $1.81 | Order filled in 12 ms", C_TEXT_DIM)],
            [("Performance: Cumulative ROI +24.8% vs Buy&Hold benchmark +6.2% (Sharpe Ratio: 2.41)", C_CYAN)]
        ],
        "status_left": "PORTFOLIO: $12.48K | ROI: +24.8% | SHARPE: 2.41 | ORDER: BUY | INDICATOR: MACD",
        "status_right": "Quantitative Trading • LSTM • Python"
    },

    "silicium-eip": {
        "title": "silicium-eip — Multi-Agent Distributed Sensor Mesh & Cloud Gateway",
        "subtitle": "Edge Processing, Distributed Consensus & Real-Time Telemetry",
        "badge": "● 12 NODES CLUSTER",
        "badge_color": C_CYAN,
        "dir": "~/Silicium-Project",
        "cmd": "silicium-node --cluster-join 192.168.1.100:8443",
        "lines": [
            [("[SILICIUM CORE] ", C_CYAN), ("Node online: ID=sil-node-eu-west-04 | Linux x86_64", C_TEXT_WHITE)],
            [("  Network Interface: 192.168.1.104:8443 | TLS 1.3 mutual auth active", C_TEXT_DIM)],
            [("[DISCOVERY] ", C_BLUE), ("mDNS mesh broadcast: Found 12 peer nodes in local subnet", C_TEXT_WHITE)],
            [("[CONSENSUS] ", C_PURPLE), ("Raft group quorum established (Leader: sil-node-eu-west-01)", C_TEXT_WHITE)],
            [("", C_TEXT_WHITE)],
            [("[DISTRIBUTED WORKLOAD ASSIGNMENT] ", C_YELLOW, True)],
            [("  Job #819: Silicium Raytracer Tile Render", C_TEXT_WHITE)],
            [("  Assigned Viewport Tile : (X: 1280..1920, Y: 720..1080) | 16 samples/px", C_TEXT_DIM)],
            [("  Compute Throughput     : 4.8 GFLOPS | Local worker status: ACTIVE", C_GREEN)],
            [("  Tile Render Time       : 1.14s | Checksum: 0x9f2a4b | Status: UPLOADED", C_GREEN)],
            [("", C_TEXT_WHITE)],
            [("[TELEMETRY STREAM] ", C_GREEN), ("WebSocket gateway: 240 sensor packets/sec", C_TEXT_WHITE)],
            [("  Avg Mesh Latency: 1.2 ms | Zero packet drop | Heartbeat: 1000ms", C_CYAN)],
            [("  Memory RSS: 38.4 MB | CPU Usage: 4.2% (Idle) / 88.4% (Job compute)", C_TEXT_DIM)]
        ],
        "status_left": "CLUSTER: 12 NODES | CONSENSUS: RAFT | WORKLOAD: DISTRIBUTED | LATENCY: 1.2ms",
        "status_right": "Distributed Systems • Tauri • Rust / C++"
    },

    "panoramix": {
        "title": "panoramix — Multithreaded POSIX Concurrency Battle Simulator",
        "subtitle": "Pthreads, Mutex Locks & Counting Semaphores",
        "badge": "● CONCURRENCY PASS",
        "badge_color": C_GREEN,
        "dir": "~/panoramix",
        "cmd": "./panoramix 4 5 2 2",
        "lines": [
            [("[INIT] ", C_BLUE), ("Villagers: 4 | Pot Capacity: 5 servings | Battles: 2 | Refills: 2", C_TEXT_WHITE)],
            [("Druid: I'm ready... but sleepy...", C_TEXT_DIM)],
            [("Villager 0: Going into battle!", C_CYAN)],
            [("Villager 2: Going into battle!", C_CYAN)],
            [("Villager 1: Going into battle!", C_CYAN)],
            [("Villager 3: Going into battle!", C_CYAN)],
            [("Villager 0: I need a drink... I see 5 servings left.", C_YELLOW)],
            [("Villager 0: Take that roman scum! Only 1 left.", C_GREEN)],
            [("Villager 2: I need a drink... I see 4 servings left.", C_YELLOW)],
            [("Villager 2: Take that roman scum! Only 0 left.", C_GREEN)],
            [("Villager 3: Hey Pano wake up! We need more potion.", C_RED, True)],
            [("Druid: Ah! Yes, yes, I'm awake! Working on it! Beware I can only make 1 more refills.", C_PURPLE)],
            [("Villager 1: I need a drink... I see 5 servings left.", C_YELLOW)],
            [("Villager 1: Take that roman scum! Only 0 left.", C_GREEN)],
            [("", C_TEXT_WHITE)],
            [("[CLEANUP] ", C_GREEN, True), ("All 4 villagers completed battles. Mutexes & semaphores cleanly freed.", C_GREEN)]
        ],
        "status_left": "THREADS: 5 | MUTEX: POSIX | SEMAPHORE: COUNTING | RACE CONDITIONS: 0 | PASS",
        "status_right": "Multithreading • Pthreads • Concurrency"
    },

    "popeye": {
        "title": "popeye — Containerized Multi-Tier Microservices Architecture",
        "subtitle": "Docker Compose, PostgreSQL, Redis, Flask & Node.js",
        "badge": "● 5 CONTAINERS HEALTHY",
        "badge_color": C_CYAN,
        "dir": "~/popeye",
        "cmd": "docker-compose up -d && docker-compose ps",
        "lines": [
            [("[DOCKER COMPOSE] ", C_BLUE), ("Building isolated overlay networks and volumes...", C_TEXT_WHITE)],
            [("  Network popeye_poll-tier   : bridge [Created]", C_TEXT_DIM)],
            [("  Network popeye_result-tier : bridge [Created]", C_TEXT_DIM)],
            [("  Network popeye_back-tier   : bridge [Created]", C_TEXT_DIM)],
            [("  Volume  popeye_db-data     : local  [Created]", C_TEXT_DIM)],
            [("", C_TEXT_WHITE)],
            [("CONTAINER STATUS SUMMARY:", C_TEXT_WHITE, True)],
            [("  popeye_poll_1   | python app.py      | Up 42m | 0.0.0.0:5000->80/tcp  [HEALTHY]", C_GREEN)],
            [("  popeye_result_1 | node server.js     | Up 42m | 0.0.0.0:5001->80/tcp  [HEALTHY]", C_GREEN)],
            [("  popeye_worker_1 | dotnet Worker.dll  | Up 42m | (Queue processor)     [HEALTHY]", C_GREEN)],
            [("  popeye_db_1     | postgres           | Up 42m | 0.0.0.0:5432->5432/tcp[HEALTHY]", C_GREEN)],
            [("  popeye_redis_1  | redis-server       | Up 42m | 0.0.0.0:6379->6379/tcp[HEALTHY]", C_GREEN)],
            [("", C_TEXT_WHITE)],
            [("[HEALTHCHECK] ", C_GREEN, True), ("All 5 microservices communicating cleanly across tier boundaries.", C_GREEN)],
            [("Database schema initialized via /docker-entrypoint-initdb.d/schema.sql.", C_TEXT_DIM)]
        ],
        "status_left": "TIERS: 3 | SERVICES: 5 | REDIS: OK | POSTGRES: OK | HTTP 5000/5001: 200 OK",
        "status_right": "Docker • Microservices • DevOps"
    },

    "the-plazza": {
        "title": "the-plazza — Multiprocess IPC Kitchen Order Dispatcher",
        "subtitle": "POSIX Message Queues, Thread Pools & Cook Synchronization",
        "badge": "● IPC THREADPOOL",
        "badge_color": C_YELLOW,
        "dir": "~/the-plazza",
        "cmd": "./plazza 2.0 5 2000",
        "lines": [
            [("[PLAZZA CONTROLLER] ", C_BLUE), ("Cooking multiplier: 2.0 | Cooks per kitchen: 5 | Restock: 2000ms", C_TEXT_WHITE)],
            [("➜ Order input: \"margarita S x2; americana L x1; fantasia M x3\"", C_YELLOW)],
            [("[DISPATCHER] Parsed 6 pizzas across 3 distinct menu orders.", C_TEXT_DIM)],
            [("  Spawning Kitchen Process #1 (PID: 4921) via Named Pipe /tmp/plazza_k1", C_CYAN)],
            [("  Spawning Kitchen Process #2 (PID: 4922) via Named Pipe /tmp/plazza_k2", C_CYAN)],
            [("", C_TEXT_WHITE)],
            [("Kitchen 1: Cook 0 started preparing Margarita (Small) [Baking: 2.0s]", C_TEXT_WHITE)],
            [("Kitchen 1: Cook 1 started preparing Margarita (Small) [Baking: 2.0s]", C_TEXT_WHITE)],
            [("Kitchen 2: Cook 0 started preparing Americana (Large) [Baking: 4.0s]", C_TEXT_WHITE)],
            [("Kitchen 1: [READY] Pizza Margarita (Small) completed! Cook 0 freed.", C_GREEN)],
            [("Kitchen 2: Cook 1 started preparing Fantasia (Medium) [Baking: 8.0s]", C_TEXT_WHITE)],
            [("Kitchen 1: [READY] Pizza Margarita (Small) completed! Cook 1 freed.", C_GREEN)],
            [("", C_TEXT_WHITE)],
            [("[CLEANUP] ", C_GREEN, True), ("All orders fulfilled. Inactive kitchens timed out (5s) and cleanly reaped.", C_GREEN)]
        ],
        "status_left": "PROCESSES: MULTI-FORK | IPC: NAMED PIPES | THREADPOOL: 5 COOKS/KITCHEN | PASS",
        "status_right": "IPC • POSIX Concurrency • C++"
    },

    "zappy": {
        "title": "zappy — Autonomous Multi-Agent TCP Network Game Engine",
        "subtitle": "Multiplexed C Network Server & Autonomous AI Client",
        "badge": "● TCP SERVER 4242",
        "badge_color": C_CYAN,
        "dir": "~/zappy",
        "cmd": "./zappy_server -p 4242 -x 10 -y 10 -n team1 team2 -c 5 -f 100",
        "lines": [
            [("==== Server Information: ====", C_CYAN, True)],
            [("    Server IP: 192.168.1.28 | Port Number: 4242", C_TEXT_WHITE)],
            [("    Map Width: 10 | Map Height: 10 | Frequency: 100 Hz", C_TEXT_WHITE)],
            [("    Team 1: team1 (5 slots available)", C_YELLOW)],
            [("    Team 2: team2 (5 slots available)", C_YELLOW)],
            [("==============================", C_CYAN)],
            [("", C_TEXT_WHITE)],
            [("[SELECT LOOP] ", C_BLUE), ("Multiplexed non-blocking socket loop active on fd 3", C_TEXT_WHITE)],
            [("New client connected on socket fd 4 from 192.168.1.45:51230", C_TEXT_DIM)],
            [("Client 4 authenticated as team: \"team1\" | Player #1 spawned at (x=4, y=7, Level 1)", C_GREEN)],
            [("Client 4 command: \"Forward\" -> OK (Time unit: 7/100 s)", C_TEXT_WHITE)],
            [("Client 4 command: \"Look\" -> [player, food, sibur, , deraumere,,]", C_CYAN)],
            [("Client 4 command: \"Take food\" -> OK (Inventory: 10 food)", C_GREEN)],
            [("World tick 100: Resource generation cycle executed (Linemate, Deraumere spawned)", C_TEXT_DIM)]
        ],
        "status_left": "PORT: 4242 | TICK: 100Hz | SELECT() NON-BLOCKING | CLIENTS: 5/TEAM | PASS",
        "status_right": "TCP Network • Socket Multiplexing • C"
    },

    "109titration": {
        "title": "109titration — Numerical Differentiation pH Titration Analysis",
        "subtitle": "First & Second Discrete Derivative Approximation",
        "badge": "● EQUIVALENCE: 8.0 mL",
        "badge_color": C_GREEN,
        "dir": "~/109titration",
        "cmd": "./109titration titration_curve.csv",
        "lines": [
            [("[INPUT DATA] ", C_BLUE), ("Reading titration_curve.csv (Acid-Base neutralization curve)", C_TEXT_WHITE)],
            [("  Volume interval: 0.0 mL -> 12.0 mL | Step: 0.5 mL - 0.2 mL near equivalence", C_TEXT_DIM)],
            [("", C_TEXT_WHITE)],
            [("First Derivative (pH' = d(pH)/dV):", C_CYAN, True)],
            [("  2.0 ml -> 0.15          7.5 ml -> 1.88          8.2 ml -> 5.60", C_TEXT_WHITE)],
            [("  4.0 ml -> 0.18          7.8 ml -> 5.60          8.5 ml -> 1.87", C_TEXT_WHITE)],
            [("  6.0 ml -> 0.30          8.0 ml -> 10.00 (PEAK)  9.0 ml -> 0.80", C_YELLOW, True)],
            [("  7.0 ml -> 0.80                                  10.0 ml -> 0.30", C_TEXT_WHITE)],
            [("", C_TEXT_WHITE)],
            [("Equivalence Point Detection:", C_TEXT_DIM)],
            [("  >> Equivalence point at 8.0 ml (pH = 7.00)", C_GREEN, True)],
            [("", C_TEXT_WHITE)],
            [("Second Derivative (pH'' = d²(pH)/dV²):", C_PURPLE, True)],
            [("  7.0 ml -> +1.05         7.8 ml -> +16.25        8.2 ml -> -16.25", C_TEXT_WHITE)],
            [("  7.5 ml -> +6.00         8.0 ml -> 0.00 (ZERO)   8.5 ml -> -6.00", C_GREEN, True)],
            [("Inflection point validated: Second derivative zero-crossing at V_eq = 8.00 mL", C_TEXT_DIM)]
        ],
        "status_left": "V_EQ: 8.00 mL | DERIVATIVE: DISCRETE DIFFERENCES | ZERO-CROSS: CONFIRMED",
        "status_right": "Numerical Calculus • Chemistry Analytics • Python"
    },

    "groundhog": {
        "title": "groundhog — Real-Time Streaming Financial Statistics Engine",
        "subtitle": "Moving Standard Deviation, Rate of Increase & Trend Switches",
        "badge": "● STREAM ANALYSIS",
        "badge_color": C_CYAN,
        "dir": "~/groundhog",
        "cmd": "./groundhog 7 < market_telemetry.stream",
        "lines": [
            [("[STREAMING ENGINE] ", C_BLUE), ("Sliding window period: 7 samples | Source: STDIN", C_TEXT_WHITE)],
            [("  g = temperature increase average | r = relative temperature evolution %", C_TEXT_DIM)],
            [("  s = moving standard deviation", C_TEXT_DIM)],
            [("", C_TEXT_WHITE)],
            [("g=0.43    r=5%     s=0.62", C_TEXT_WHITE)],
            [("g=0.43    r=5%     s=0.62", C_TEXT_WHITE)],
            [("g=0.43    r=5%     s=0.70", C_TEXT_WHITE)],
            [("g=0.36    r=-7%    s=0.80   --> a switch occurs!", C_YELLOW, True)],
            [("g=1.79    r=39%    s=3.45   --> a switch occurs!", C_YELLOW, True)],
            [("g=1.86    r=55%    s=4.45", C_TEXT_WHITE)],
            [("g=1.86    r=54%    s=4.93", C_TEXT_WHITE)],
            [("g=1.86    r=52%    s=5.04", C_TEXT_WHITE)],
            [("g=1.79    r=40%    s=4.59", C_TEXT_WHITE)],
            [("", C_TEXT_WHITE)],
            [("Global tendency switched 2 times", C_GREEN, True)],
            [("5 weirdest values identified: [35.20, 34.80, 20.00, 20.50, 21.00]", C_CYAN)]
        ],
        "status_left": "WINDOW: 7 SAMPLES | SWITCHES: 2 | OUTLIERS: 5 FLAGGED | STREAM: EOF CLEAN",
        "status_right": "Streaming Statistics • Financial Math • Python"
    },

    "math-algorithms": {
        "title": "math-algorithms — Scientific Numerical Computing Suite (101-110)",
        "subtitle": "Vectors, Affine Matrices, Taylor Series & Numerical Integrals",
        "badge": "● 9 MODULES PASS",
        "badge_color": C_GREEN,
        "dir": "~/math-algorithms",
        "cmd": "./101pong 1 2 3 4 5 6 2 && ./102architect 1 2 -t 3 4 -r 45",
        "lines": [
            [("[101 PONG - 3D BALLISTIC VELOCITY PREDICTOR]", C_BLUE, True)],
            [("  The velocity vector of the ball is: ", C_TEXT_DIM), ("(3.00, 3.00, 3.00)", C_YELLOW)],
            [("  At time t + 2, ball coordinates will be: ", C_TEXT_DIM), ("(10.00, 11.00, 12.00)", C_GREEN)],
            [("  Paddle intersection angle: 45.00 degrees (Paddle miss predicted)", C_TEXT_DIM)],
            [("", C_TEXT_WHITE)],
            [("[102 ARCHITECT - HOMOGENEOUS TRANSFORMATION MATRICES]", C_PURPLE, True)],
            [("  Translation matrix (dx=3, dy=4):    Rotation matrix (theta=45°):", C_TEXT_DIM)],
            [("    [ 1.00  0.00  3.00 ]                  [  0.71 -0.71  0.00 ]", C_CYAN)],
            [("    [ 0.00  1.00  4.00 ]                  [  0.71  0.71  0.00 ]", C_CYAN)],
            [("    [ 0.00  0.00  1.00 ]                  [  0.00  0.00  1.00 ]", C_CYAN)],
            [("  Resulting point: (1.00, 2.00) transformed to (2.12, 4.95)", C_GREEN, True)],
            [("", C_TEXT_WHITE)],
            [("[NUMERICAL SUITE VERIFICATION]", C_TEXT_WHITE, True)],
            [("  103cipher: Invertible hill matrices | 104intersection: Quadric surface rays", C_TEXT_DIM)],
            [("  105torus: Newton-Raphson roots      | 110borwein: Simpson numerical integration", C_TEXT_DIM)],
            [("Status: All 9 numerical modules validated with 100% precision tolerance.", C_GREEN)]
        ],
        "status_left": "SUITE: 9 MODULES | MATRICES: 3x3 HOMOGENEOUS | NEWTON-RAPHON: CONVERGED",
        "status_right": "Applied Mathematics • Linear Algebra • C"
    },

    "palindrome": {
        "title": "palindrome — Iterative Number Palindrome Convergence Engine",
        "subtitle": "Base-N Digit Reversal & Fixed-Point Convergence",
        "badge": "● CONVERGED BASE 10",
        "badge_color": C_GREEN,
        "dir": "~/palindrome",
        "cmd": "./palindrome -n 4782 -b 10 -imin 0 -imax 100",
        "lines": [
            [("[PARAMETERS] ", C_BLUE), ("Target Number: 4782 | Base: 10 | Iteration Window: [0, 100]", C_TEXT_WHITE)],
            [("Starting reverse-addition algorithm (Lychrel sequence generator):", C_TEXT_DIM)],
            [("", C_TEXT_WHITE)],
            [("  Iteration 1: 4782 + 2874 = 7656  (Non-palindromic)", C_TEXT_WHITE)],
            [("  Iteration 2: 7656 + 6567 = 14223 (Non-palindromic)", C_TEXT_WHITE)],
            [("  Iteration 3: 14223 + 32241 = 46464 (PALINDROME DETECTED!)", C_GREEN, True)],
            [("", C_TEXT_WHITE)],
            [("RESULT: ", C_TEXT_WHITE, True), ("4782 leads to 46464 in 3 iteration(s) in base 10", C_GREEN, True)],
            [("", C_TEXT_WHITE)],
            [("[INVERSE MODE] ", C_PURPLE), ("./palindrome -p 363 -b 10 (Finding integer seeds):", C_TEXT_WHITE)],
            [("  3  leads to 363 in 6 iteration(s) in base 10", C_CYAN)],
            [("  33 leads to 363 in 5 iteration(s) in base 10", C_CYAN)],
            [("All candidate roots discovered. Zero overflow on 64-bit uint.", C_TEXT_DIM)]
        ],
        "status_left": "NUMBER: 4782 | PALINDROME: 46464 | ITERS: 3 | BASE: 10 | STATUS: PASS",
        "status_right": "Number Theory • Combinatorics • C"
    },

    "projtester": {
        "title": "projtester — Automated Process Regression Testing Supervisor",
        "subtitle": "Directory Tree Traversal, Exit Codes & Timeout Analysis",
        "badge": "● 48/48 TESTS PASS",
        "badge_color": C_GREEN,
        "dir": "~/projtester",
        "cmd": "./projTester test_suites/ /usr/bin/my_ls /tmp/report.log",
        "lines": [
            [("[TEST RUNNER] ", C_BLUE), ("Scanning test suite hierarchy: test_suites/ (Depth: 3)", C_TEXT_WHITE)],
            [("Target Binary Under Test: /usr/bin/my_ls", C_TEXT_DIM)],
            [("", C_TEXT_WHITE)],
            [("  [RUNNING] test_basic_ls ........................... ", C_TEXT_DIM), ("[PASS]", C_GREEN), (" (0.01s, exit: 0)", C_TEXT_DIM)],
            [("  [RUNNING] test_flag_l ............................. ", C_TEXT_DIM), ("[PASS]", C_GREEN), (" (0.01s, exit: 0)", C_TEXT_DIM)],
            [("  [RUNNING] test_flag_R_nested ...................... ", C_TEXT_DIM), ("[PASS]", C_GREEN), (" (0.03s, exit: 0)", C_TEXT_DIM)],
            [("  [RUNNING] test_flag_d_directory ................... ", C_TEXT_DIM), ("[PASS]", C_GREEN), (" (0.01s, exit: 0)", C_TEXT_DIM)],
            [("  [RUNNING] test_invalid_path ....................... ", C_TEXT_DIM), ("[PASS]", C_GREEN), (" (0.01s, exit: 84)", C_TEXT_DIM)],
            [("  [RUNNING] test_permission_denied .................. ", C_TEXT_DIM), ("[PASS]", C_GREEN), (" (0.01s, exit: 84)", C_TEXT_DIM)],
            [("", C_TEXT_WHITE)],
            [("TEST SUITE SUMMARY:", C_TEXT_WHITE, True)],
            [("  Total Test Scenarios : ", C_TEXT_DIM), ("48", C_TEXT_WHITE), (" | Passed: ", C_TEXT_DIM), ("48", C_GREEN, True), (" | Failed: ", C_TEXT_DIM), ("0", C_GREEN)],
            [("  Success Rate         : ", C_TEXT_DIM), ("100.0%", C_GREEN, True), (" | Time: ", C_TEXT_DIM), ("0.48s total", C_CYAN)],
            [("Report written to /tmp/report.log with full stdout/stderr diffs.", C_TEXT_DIM)]
        ],
        "status_left": "TESTS: 48 | PASSED: 48 | FAILED: 0 | TIMEOUT: 0 | SUCCESS: 100% | EXIT: 0",
        "status_right": "Testing Framework • Process Supervision • C"
    },

    "sbmlparser": {
        "title": "sbmlparser — SBML XML Biochemical Reaction Network Parser",
        "subtitle": "Stoichiometry Matrix, Reactants, Products & JSON Export",
        "badge": "● XML PARSER PASS",
        "badge_color": C_CYAN,
        "dir": "~/sbmlparser",
        "cmd": "./SBMLparser glycolysis_pathway.sbml -i hexokinase_reaction -e",
        "lines": [
            [("[XML PARSER] ", C_BLUE), ("Reading SBML Level 3 Version 1: glycolysis_pathway.sbml", C_TEXT_WHITE)],
            [("  Model ID: \"glycolysis_pathway\" | Compartments: 1 | Species: 4 | Reactions: 1", C_TEXT_DIM)],
            [("", C_TEXT_WHITE)],
            [("Reaction Extraction ID: \"hexokinase_reaction\" (Reversible: false)", C_YELLOW, True)],
            [("  Reactants:", C_CYAN)],
            [("    - Glucose (stoichiometry: 1, compartment: cytosol)", C_TEXT_WHITE)],
            [("    - ATP     (stoichiometry: 1, compartment: cytosol)", C_TEXT_WHITE)],
            [("  Products:", C_GREEN)],
            [("    - G6P     (stoichiometry: 1, compartment: cytosol)", C_TEXT_WHITE)],
            [("    - ADP     (stoichiometry: 1, compartment: cytosol)", C_TEXT_WHITE)],
            [("", C_TEXT_WHITE)],
            [("Stoichiometric Chemical Equation:", C_TEXT_DIM)],
            [("  Glucose + ATP -> G6P + ADP", C_GREEN, True)],
            [("", C_TEXT_WHITE)],
            [("[JSON EXPORT] ", C_PURPLE), ("./SBMLparser glycolysis_pathway.sbml -json -> 100% Valid JSON schema", C_TEXT_WHITE)]
        ],
        "status_left": "SBML: LEVEL 3 | SPECIES: 4 | REACTIONS: 1 | STOICHIOMETRY: OK | EXPORT: JSON",
        "status_right": "Systems Biology • XML Schema • C"
    },

    "arcade": {
        "title": "arcade — Modular Multi-Library Gaming Platform",
        "subtitle": "Hot-Reload Dynamic Shared Objects (.so) Engine",
        "badge": "● MODULAR ARCHITECTURE",
        "badge_color": C_PURPLE,
        "dir": "~/arcade",
        "cmd": "./arcade ./lib/arcade_sfml.so",
        "lines": [
            [("[ARCADE LOADER] ", C_BLUE), ("Inspecting dynamic library: ./lib/arcade_sfml.so", C_TEXT_WHITE)],
            [("  dlopen() / dlsym() symbol verification: createLibInstance, destroyLibInstance", C_TEXT_DIM)],
            [("  Registered Graphics: [ arcade_sfml.so (ACTIVE), arcade_sdl2.so, arcade_ncurses.so ]", C_CYAN)],
            [("  Registered Games   : [ arcade_pacman.so (ACTIVE), arcade_nibbler.so, arcade_solarfox.so ]", C_YELLOW)],
            [("", C_TEXT_WHITE)],
            [("[GAME LOOP] ", C_GREEN), ("Pacman game state running at 60.0 FPS locked", C_TEXT_WHITE)],
            [("  Score: 4,820 | Lives: 3 | Dots remaining: 84 | Ghosts: 4 active", C_TEXT_WHITE)],
            [("", C_TEXT_WHITE)],
            [("[HOT-SWAP EVENT] ", C_YELLOW, True), ("User pressed 'G': Switching renderer to arcade_ncurses.so", C_YELLOW)],
            [("  Serializing game memory snapshot... [OK]", C_TEXT_DIM)],
            [("  Unloading SFML window context (dlclose)... [OK]", C_TEXT_DIM)],
            [("  Loading ncurses terminal renderer (dlopen)... [OK]", C_TEXT_DIM)],
            [("  Restoring Pacman game state... [RESUMED AT 60 FPS]", C_GREEN, True)],
            [("Zero memory leaks across dynamic library transitions (Valgrind clean).", C_TEXT_DIM)]
        ],
        "status_left": "LIBRARIES: HOT-RELOAD | RENDERERS: 3 | GAMES: 3 | FPS: 60.0 | LEAKS: 0",
        "status_right": "Dynamic Polymorphism • C++20 • dlopen"
    },

    "myhunter": {
        "title": "myhunter — 2D Interactive Duck Hunt Game Engine",
        "subtitle": "CSFML Sprite Animation, Event Loop & Hitbox Math",
        "badge": "● 60 FPS CSFML",
        "badge_color": C_GREEN,
        "dir": "~/myhunter",
        "cmd": "./my_hunter",
        "lines": [
            [("[CSFML INIT] ", C_BLUE), ("Creating render window: 1280x768 @ 32bpp (V-Sync enabled)", C_TEXT_WHITE)],
            [("  Texture atlas loaded: sprites/duck_fly.png (3 frames animation, rect: 110x110)", C_TEXT_DIM)],
            [("  Parallax background layers loaded: foreground, marsh reeds, clouds", C_TEXT_DIM)],
            [("", C_TEXT_WHITE)],
            [("[GAME LOOP - FRAME #0420] ", C_GREEN), ("Delta time: 0.0166s (60.1 FPS)", C_TEXT_WHITE)],
            [("  Duck Target #01 : Pos (420, 310) | Velocity: (350 px/s, -40 px/s)", C_CYAN)],
            [("  Duck Target #02 : Pos (180, 220) | Velocity: (280 px/s, +20 px/s)", C_CYAN)],
            [("  Mouse Click Event: Cursor at (428, 305)", C_YELLOW)],
            [("    -> Axis-Aligned Bounding Box (AABB) intersection: ", C_TEXT_DIM), ("HIT CONFIRMED!", C_GREEN, True)],
            [("  Score: +500 | Current Score: 14,200 | Streak: x4 | Highscore: 42,000", C_YELLOW)],
            [("  Audio playback: sounds/shot.ogg (Spatial stereo sound trigger)", C_TEXT_DIM)],
            [("CPU Usage: 2.1% | GPU VRAM: 18 MB | Zero dropped frames", C_TEXT_DIM)]
        ],
        "status_left": "CSFML: 2D SPRITES | RESOLUTION: 1280x768 | FPS: 60.1 | HITBOX: AABB | PASS",
        "status_right": "Game Loop • Event Polling • CSFML"
    },

    "mypaint": {
        "title": "mypaint — 2D Raster Image & Digital Painting Studio",
        "subtitle": "CSFML Canvas Layers, Brushes & Color Compositing",
        "badge": "● RGBA PIXEL ENGINE",
        "badge_color": C_PURPLE,
        "dir": "~/mypaint",
        "cmd": "./my_paint",
        "lines": [
            [("[MYPAINT CORE] ", C_BLUE), ("Initialized canvas buffer: 1920x1080 RGBA (8.29 MB pixel buffer)", C_TEXT_WHITE)],
            [("Tool Palette active:", C_TEXT_DIM)],
            [("  - Brush     : Calligraphic (Radius: 8px, Hardness: 0.8, Opacity: 100%)", C_CYAN)],
            [("  - Color     : #38bdf8 (R:56, G:189, B:248, A:255)", C_CYAN)],
            [("  - Blend mode: Alpha Compositing (Porter-Duff Over formula)", C_YELLOW)],
            [("", C_TEXT_WHITE)],
            [("Layer Stack:", C_TEXT_DIM)],
            [("  Layer 0 [Background] : White fill (Visible, Locked)", C_TEXT_WHITE)],
            [("  Layer 1 [Outline]    : Vector line art (Visible, Opacity: 100%)", C_TEXT_WHITE)],
            [("  Layer 2 [Coloring]   : Shading pass (Active, Opacity: 85%)", C_GREEN)],
            [("", C_TEXT_WHITE)],
            [("Mouse Drag Event: (x: 410..520, y: 310..420) -> 142 brush stamps rendered", C_TEXT_DIM)],
            [("[EXPORT] File -> Save as PNG: /tmp/artwork_layer_composite.png (Saved cleanly)", C_GREEN, True)]
        ],
        "status_left": "CANVAS: 1920x1080 | RGBA 32-BIT | LAYERS: 3 | BRUSH: ANTI-ALIASED | EXPORT: PNG",
        "status_right": "Raster Graphics • Blend Modes • CSFML"
    },

    "myradar": {
        "title": "myradar — Real-Time Air Traffic Control & Collision Simulation",
        "subtitle": "Spatial Quadtree Partitioning & Flight Trajectory Vectors",
        "badge": "● 5,000 AIRCRAFT 60FPS",
        "badge_color": C_GREEN,
        "dir": "~/myradar",
        "cmd": "./my_radar scripts/dense_airspace_5000.script",
        "lines": [
            [("[SIMULATION ENGINE] ", C_BLUE), ("Window: 1920x1080 | Airspace density: 5,000 aircraft", C_TEXT_WHITE)],
            [("  Loaded: 5,000 flight corridors | 12 ground control towers with safe zones", C_TEXT_DIM)],
            [("", C_TEXT_WHITE)],
            [("[SPATIAL PARTITIONING - DYNAMIC QUADTREE]", C_PURPLE, True)],
            [("  Quadtree depth: 8 levels | Leaf capacity: 16 entities", C_TEXT_DIM)],
            [("  Broad-phase collision reduction:", C_CYAN)],
            [("    Naive checks: 12,497,500 pairs -> Quadtree checks: 18,420 pairs (99.85% pruned)", C_GREEN)],
            [("  Narrow-phase circle-to-circle collision tests: 142 tested | 0 collisions", C_GREEN)],
            [("", C_TEXT_WHITE)],
            [("[RADAR PPI DISPLAY] ", C_GREEN), ("Phosphor sweep beam at 142.4° with exponential visual decay", C_TEXT_WHITE)],
            [("  Aircraft flight vectors: Heading angles and speed vectors rendered", C_TEXT_DIM)],
            [("  Safe landing zones: 12 towers maintaining 100% collision-free transit", C_TEXT_DIM)],
            [("Frame Rate: 60.2 FPS | Frame Time: 16.5 ms | Memory RSS: 14.2 MB", C_YELLOW)]
        ],
        "status_left": "ENTITIES: 5,000 | QUADTREE: 8 LEVELS | PRUNED: 99.85% | FPS: 60.2 | CRASHES: 0",
        "status_right": "Spatial Partitioning • Quadtree • CSFML"
    },

    "myrpg": {
        "title": "myrpg — 2D Action-RPG Engine with Quest State Machine",
        "subtitle": "Tilemap Layering, Particle Systems & Combat Stats",
        "badge": "● 2D ACTION-RPG",
        "badge_color": C_PURPLE,
        "dir": "~/myrpg",
        "cmd": "./my_rpg",
        "lines": [
            [("[RPG ENGINE] ", C_BLUE), ("Loading world chunk: maps/chunk_forest_01.json (Tile: 32x32)", C_TEXT_WHITE)],
            [("  Layers rendered: Ground, Decals, Obstacles, Canopy (Z-sorted y-depth)", C_TEXT_DIM)],
            [("", C_TEXT_WHITE)],
            [("Player Character State:", C_TEXT_DIM)],
            [("  Class: Mage | Level: 14 | HP: 480/480 | Mana: 320/320", C_CYAN)],
            [("  Inventory: [Iron Staff, Health Potion x5, Ancient Rune, Quest Key]", C_TEXT_WHITE)],
            [("", C_TEXT_WHITE)],
            [("[QUEST STATE MACHINE] ", C_YELLOW)],
            [("  Active Quest: \"The Whispering Crypt\" (Stage 2/4: Explore Forest)", C_TEXT_WHITE)],
            [("  NPC Dialogue: Town Elder conversation completed -> Trigger unlocked", C_TEXT_DIM)],
            [("", C_TEXT_WHITE)],
            [("[COMBAT TRIGGER] ", C_RED), ("Encounter: Shadow Wolf (HP: 120)", C_TEXT_WHITE)],
            [("  Cast Spell: Fireball -> Damage: 84 (Critical Hit!) -> Burn effect applied", C_ORANGE)],
            [("Particle system: 250 fire sparks spawned | Audio: BGM looping cleanly", C_TEXT_DIM)]
        ],
        "status_left": "TILEMAP: 32x32 | QUEST MACHINE: ACTIVE | PARTICLES: 250 | AUDIO: STREAMING",
        "status_right": "RPG Architecture • State Machines • CSFML"
    },

    "myworld": {
        "title": "myworld — 3D Isometric Terrain Mesh Editor",
        "subtitle": "Bresenham Wireframes, Elevation Deformation & Convex Polygons",
        "badge": "● ISOMETRIC 3D MESH",
        "badge_color": C_CYAN,
        "dir": "~/myworld",
        "cmd": "./my_world",
        "lines": [
            [("[TERRAIN ENGINE] ", C_BLUE), ("Initialized 3D mesh grid: 64x64 vertices (4,096 total points)", C_TEXT_WHITE)],
            [("Isometric 2.5D Projection Formulas:", C_TEXT_DIM)],
            [("  X_iso = (X - Y) * cos(30°) | Y_iso = (X + Y) * sin(30°) - Z * scale", C_CYAN)],
            [("", C_TEXT_WHITE)],
            [("Interactive Terrain Sculpting:", C_TEXT_DIM)],
            [("  Selected vertex   : (x=18, y=24) | Current Elevation Z: 14.0m", C_TEXT_WHITE)],
            [("  Tool Selected     : Elevation Brush (Radius: 3 cells, Gaussian falloff)", C_YELLOW)],
            [("  Operation Applied : Raise terrain +4.5m with Perlin noise smoothing", C_GREEN)],
            [("", C_TEXT_WHITE)],
            [("Polygon Shading & Height-Based Colormap:", C_TEXT_DIM)],
            [("  Water (<0m: Blue) -> Grass (0-15m: Green) -> Mountain (>15m: Snow)", C_PURPLE)],
            [("  Bresenham line wireframe overlay: ACTIVE | Normal lighting: Flat", C_TEXT_WHITE)],
            [("Frame Rate: 60.0 FPS locked | Memory RSS: 16.4 MB", C_TEXT_DIM)]
        ],
        "status_left": "GRID: 64x64 | VERTICES: 4,096 | PROJECTION: ISOMETRIC | SHADING: HEIGHT GRADIENT",
        "status_right": "3D Isometric Projection • Mesh Editing • C"
    },

    "relativistic-raytracer": {
        "title": "relativistic-raytracer — 3D Raytracing Illumination Engine",
        "subtitle": "Phong Shading, Specular Reflections & Primitive Geometry",
        "badge": "● RAYTRACING 3D",
        "badge_color": C_CYAN,
        "dir": "~/relativistic-raytracer",
        "cmd": "./raytracer scenes/specular_spheres.cfg -o render.ppm",
        "lines": [
            [("[RAYTRACER CORE] ", C_BLUE), ("Parsing scene description: scenes/specular_spheres.cfg", C_TEXT_WHITE)],
            [("Scene Primitives Loaded:", C_TEXT_DIM)],
            [("  Camera: Pos (0, -100, 20), Target (0, 0, 10), Field of View: 60°", C_TEXT_WHITE)],
            [("  Sphere 1 : Center (-15, 0, 15), Radius: 10, Material: Red Plastic (Shininess 64)", C_RED)],
            [("  Sphere 2 : Center ( 15, 0, 12), Radius:  8, Material: Chrome Mirror (Refl 0.85)", C_CYAN)],
            [("  Plane    : Normal (0, 0, 1), Height: 0, Material: Checkerboard", C_YELLOW)],
            [("  Lights   : Point Light at (0, -40, 50), Color: #FFFFFF, Intensity: 1.2", C_PURPLE)],
            [("", C_TEXT_WHITE)],
            [("Rendering Pass (1920 x 1080 resolution):", C_TEXT_DIM)],
            [("  Primary camera rays cast : 2,073,600 rays", C_TEXT_WHITE)],
            [("  Secondary reflection rays: 1,420,800 rays (Max bounce recursion: 4)", C_CYAN)],
            [("  Shadow obstruction rays  : 2,073,600 rays (Hard shadow evaluation)", C_TEXT_WHITE)],
            [("[OUTPUT] ", C_GREEN, True), ("Rendered image exported to render.ppm (100% complete in 1.42s)", C_GREEN, True)],
            [("Phong illumination: Ambient + Diffuse (Lambert) + Specular (Blinn-Phong) computed.", C_TEXT_DIM)]
        ],
        "status_left": "RES: 1920x1080 | RAYS: 5.56M | BOUNCES: 4 | TIME: 1.42s | OUTPUT: PPM OK",
        "status_right": "Raytracing • Optics & Lighting • C++"
    },

    "rtype": {
        "title": "rtype — Cross-Platform Multiplayer Shoot'em Up Engine",
        "subtitle": "Entity Component System (ECS) & Binary UDP Protocol",
        "badge": "● MULTIPLAYER ECS",
        "badge_color": C_CYAN,
        "dir": "~/rtype",
        "cmd": "./bin/r-type_server 4242 & ./bin/r-type_client 127.0.0.1 4242",
        "lines": [
            [("[SERVER] ", C_BLUE), ("UDP listening on 0.0.0.0:4242 | Server tick rate: 60 Hz", C_TEXT_WHITE)],
            [("  Player 1 connected from 127.0.0.1:58412 (Entity ID #1, Color: Cyan)", C_CYAN)],
            [("  Player 2 connected from 127.0.0.1:58413 (Entity ID #2, Color: Orange)", C_ORANGE)],
            [("", C_TEXT_WHITE)],
            [("[ECS ARCHITECTURE UPDATE]", C_PURPLE, True)],
            [("  Components active: PositionComponent, VelocityComponent, Hitbox, Weapon", C_TEXT_DIM)],
            [("  Systems executing: MovementSystem, CollisionSystem, SpawnerSystem, RenderSystem", C_TEXT_DIM)],
            [("  Entities alive   : 2 Players, 18 Bydo Ennemies, 8 Plasma Wave Missiles", C_TEXT_WHITE)],
            [("", C_TEXT_WHITE)],
            [("[NETWORK SYNCHRONIZATION] ", C_GREEN)],
            [("  Binary delta compression: Packet size 38 bytes per snapshot", C_TEXT_WHITE)],
            [("  Round-Trip Time (RTT): 0.8 ms | Packet loss: 0.0%", C_GREEN)],
            [("  Player 1 fired Charged Wave Beam -> Hit detected on Bydo Cruiser!", C_YELLOW)],
            [("Game client locked @ 60.0 FPS | Audio stream: sound/laser.wav", C_TEXT_DIM)]
        ],
        "status_left": "UDP: 4242 | RTT: 0.8ms | ENTITIES: 28 | ECS: ARCHETYPE | FPS: 60.0",
        "status_right": "ECS Architecture • UDP Networking • C++"
    },

    "screensaver": {
        "title": "screensaver — Procedural Generative Graphics Visualizer",
        "subtitle": "Trigonometric Lissajous Curves & Particle Physics Attractors",
        "badge": "● PROCEDURAL ART",
        "badge_color": C_PURPLE,
        "dir": "~/screensaver",
        "cmd": "./my_screensaver 3",
        "lines": [
            [("[SCREENSAVER ENGINE] ", C_BLUE), ("Mode 3: Lorenz Strange Attractor & Particle Field", C_TEXT_WHITE)],
            [("Differential Equations System:", C_TEXT_DIM)],
            [("  dx/dt = sigma * (y - x)       | sigma = 10.0 (Prandtl number)", C_CYAN)],
            [("  dy/dt = x * (rho - z) - y     | rho   = 28.0 (Rayleigh number)", C_CYAN)],
            [("  dz/dt = x * y - beta * z      | beta  = 8/3  (Geometric ratio)", C_CYAN)],
            [("", C_TEXT_WHITE)],
            [("Particle Integration:", C_TEXT_DIM)],
            [("  Active particle pool: 10,000 independent particles", C_TEXT_WHITE)],
            [("  Numerical Integrator: 4th-Order Runge-Kutta (RK4) with dt = 0.005", C_YELLOW)],
            [("  3D Projection Euler angles: Pitch: 0.4 rad/s | Yaw: 0.2 rad/s", C_TEXT_WHITE)],
            [("  Color gradient: Velocity-mapped spectral shift (Cyan -> Magenta -> Gold)", C_PURPLE)],
            [("", C_TEXT_WHITE)],
            [("Display: 1920x1080 @ 60.0 FPS | Trail buffer decay: 0.94 alpha blend", C_GREEN)]
        ],
        "status_left": "PARTICLES: 10,000 | INTEGRATOR: RK4 | ATTRACTOR: LORENZ | FPS: 60.0",
        "status_right": "Procedural Graphics • Chaos Theory • CSFML"
    },

    "tekspice": {
        "title": "tekspice — Discrete Electronic SPICE Logic Simulator",
        "subtitle": "4071 CMOS OR Gate & Digital Pin State Transitions",
        "badge": "● LOGIC SIMULATOR",
        "badge_color": C_GREEN,
        "dir": "~/tekspice",
        "cmd": "echo -e 'a=1\\nb=0\\nsimulate\\ndisplay\\nexit' | ./nanotekspice circuits/or_gate.nts",
        "lines": [
            [("[CIRCUIT PARSER] ", C_BLUE), ("Loaded circuit file: circuits/or_gate.nts", C_TEXT_WHITE)],
            [("  Components instantiated: input a, input b, output s, 4071 or_gate", C_TEXT_DIM)],
            [("  Interconnect links: a:1 -> or_gate:1 | b:1 -> or_gate:2 | or_gate:3 -> s:1", C_CYAN)],
            [("", C_TEXT_WHITE)],
            [("> a=1", C_YELLOW)],
            [("> b=0", C_YELLOW)],
            [("> simulate", C_PURPLE)],
            [("> display", C_PURPLE)],
            [("tick: 1", C_TEXT_WHITE, True)],
            [("input(s):", C_TEXT_DIM)],
            [("  a: ", C_TEXT_DIM), ("1", C_GREEN, True)],
            [("  b: ", C_TEXT_DIM), ("0", C_RED, True)],
            [("output(s):", C_TEXT_DIM)],
            [("  s: ", C_TEXT_DIM), ("1", C_GREEN, True), (" (Logic OR Truth Table: 1 OR 0 -> 1)", C_CYAN)],
            [("", C_TEXT_WHITE)],
            [("Tristate logic evaluation: All digital flip-flops and gates stabilized in 1 tick.", C_TEXT_DIM)]
        ],
        "status_left": "CIRCUIT: 4071 CMOS | TICK: 1 | INPUTS: a=1, b=0 | OUTPUT: s=1 | STABILIZED",
        "status_right": "Discrete Logic • Circuit Simulation • C++"
    },

    "tetris": {
        "title": "tetris — Terminal Falling-Block Arcade Engine",
        "subtitle": "Ncurses Matrix Buffer, SRS Rotation & Highscore Table",
        "badge": "● RETRO NCURSES",
        "badge_color": C_YELLOW,
        "dir": "~/tetris",
        "cmd": "./tetris -l 5 --without-next",
        "lines": [
            [("+--------------------+  ", C_TEXT_MUTED), ("[TETRIS ARCADE ENGINE]", C_YELLOW, True)],
            [("|                    |  ", C_TEXT_MUTED), ("Score : ", C_TEXT_DIM), ("12,400", C_GREEN, True)],
            [("|                    |  ", C_TEXT_MUTED), ("Lines : ", C_TEXT_DIM), ("28", C_CYAN)],
            [("|        []          |  ", C_YELLOW), ("Level : ", C_TEXT_DIM), ("5", C_PURPLE)],
            [("|      [][][]        |  ", C_YELLOW), ("Next  : [HIDDEN]", C_TEXT_DIM)],
            [("|                    |  ", C_TEXT_MUTED)],
            [("|                    |  ", C_TEXT_MUTED), ("Controls:", C_TEXT_WHITE)],
            [("|                    |  ", C_TEXT_MUTED), ("  Move   : Left / Right", C_TEXT_DIM)],
            [("|      [][]          |  ", C_CYAN), ("  Rotate : Up (Super Rotation System)", C_TEXT_DIM)],
            [("|      [][]    [][]  |  ", C_CYAN), ("  Drop   : Space bar", C_TEXT_DIM)],
            [("|    [][][][][][][]  |  ", C_GREEN), ("  Pause  : 'p' | Quit: 'q'", C_TEXT_DIM)],
            [("|  [][][][][][][][][]|  ", C_GREEN), ("Highscore: 48,900", C_YELLOW)],
            [("+--------------------+  ", C_TEXT_MUTED)],
            [("Tick rate: 250ms interval (Gravity increased at level 5) | Collision: OK", C_TEXT_DIM)]
        ],
        "status_left": "GRID: 10x20 | LEVEL: 5 | SCORE: 12,400 | ROTATION: SRS | NCURSES RAW",
        "status_right": "Terminal Gaming • Matrix Geometry • C"
    },

    "42sh": {
        "title": "42sh — POSIX-Compliant Unix Shell Interpreter",
        "subtitle": "Duplex Pipes, Job Control, History, Globbing & Builtins",
        "badge": "● POSIX SHELL",
        "badge_color": C_GREEN,
        "dir": "~/42sh",
        "cmd": "./42sh",
        "lines": [
            [("[42sh POSIX INTERPRETER] ", C_BLUE), ("Builtins: cd, setenv, unsetenv, history, echo, which, jobs, fg", C_TEXT_WHITE)],
            [("42sh> cat /etc/hosts | grep localhost | tr 'a-z' 'A-Z' > /tmp/resolved.log && ls -l /tmp/resolved.log", C_YELLOW)],
            [("-rw-r--r-- 1 lfernandes lfernandes 24 Oct 06 21:04 /tmp/resolved.log", C_TEXT_WHITE)],
            [("", C_TEXT_WHITE)],
            [("42sh> cat /tmp/resolved.log", C_YELLOW)],
            [("127.0.0.1   LOCALHOST", C_CYAN)],
            [("::1         LOCALHOST", C_CYAN)],
            [("", C_TEXT_WHITE)],
            [("42sh> sleep 100 &", C_YELLOW)],
            [("[1] 4981", C_TEXT_DIM)],
            [("42sh> jobs", C_YELLOW)],
            [("[1]+  Running    sleep 100 & (PID: 4981)", C_TEXT_WHITE)],
            [("42sh> fg %1", C_YELLOW)],
            [("^C (SIGINT cleanly forwarded to foreground process group)", C_RED)],
            [("", C_TEXT_WHITE)],
            [("Pipeline status: Exit code 0 | Signal handling (SIGINT, SIGTSTP) validated.", C_GREEN)]
        ],
        "status_left": "PIPELINES: MULTI-STAGE | FORK/EXECVE | JOB CONTROL: ACTIVE | POSIX: PASS",
        "status_right": "Unix Shell • Systems Programming • C"
    },

    "asm-minilibc": {
        "title": "asm-minilibc — Pure x86_64 NASM Assembly Standard C Library",
        "subtitle": "System V ABI Compliant String & Memory Primitives",
        "badge": "● 100% PURE ASM",
        "badge_color": C_PURPLE,
        "dir": "~/asm-minilibc",
        "cmd": "./tests_minilibc --benchmark",
        "lines": [
            [("[NASM LIBASM BENCHMARK] ", C_PURPLE), ("Shared object: libasm.so (ELF64 System V ABI)", C_TEXT_WHITE)],
            [("Function      NASM Pure Assembly Impl         glibc Reference    Status", C_TEXT_WHITE, True)],
            [("-------------------------------------------------------------------------", C_TEXT_MUTED)],
            [("strlen()      repne scasb / quadword vector   0.021 ns/byte      ", C_TEXT_WHITE), ("[PASS - MATCH]", C_GREEN)],
            [("strcmp()      repe cmpsb                      0.034 ns/byte      ", C_TEXT_WHITE), ("[PASS - MATCH]", C_GREEN)],
            [("strncmp()     bounded register comparison     0.032 ns/byte      ", C_TEXT_WHITE), ("[PASS - MATCH]", C_GREEN)],
            [("memcpy()      rep movsb (ERMS optimized)      0.012 ns/byte      ", C_TEXT_WHITE), ("[PASS - MATCH]", C_GREEN)],
            [("memset()      rep stosb                       0.010 ns/byte      ", C_TEXT_WHITE), ("[PASS - MATCH]", C_GREEN)],
            [("strchr()      scan for character in string    0.024 ns/byte      ", C_TEXT_WHITE), ("[PASS - MATCH]", C_GREEN)],
            [("strstr()      Boyer-Moore substring scan      0.048 ns/byte      ", C_TEXT_WHITE), ("[PASS - MATCH]", C_GREEN)],
            [("strcasecmp()  case-insensitive byte compare   0.038 ns/byte      ", C_TEXT_WHITE), ("[PASS - MATCH]", C_GREEN)],
            [("", C_TEXT_WHITE)],
            [("Suite summary: 14/14 NASM functions passed all edge-case tests (NULL, empty, off-by-one).", C_GREEN)],
            [("Zero external C library dependency: 100% pure assembly instructions.", C_TEXT_DIM)]
        ],
        "status_left": "ARCH: x86_64 | ABI: SYSTEM V | FUNCTIONS: 14 | TESTS: 100% PASS | ZERO GLIBC",
        "status_right": "x86_64 NASM • Assembly • Low-Level ABI"
    },

    "c-programming-bootcamp": {
        "title": "c-programming-bootcamp — C Systems & Algorithms Bootcamp Suite",
        "subtitle": "18 Modules: Pointers, Memory Allocators, Trees & Bitwise Ops",
        "badge": "● 18/18 MODULES PASS",
        "badge_color": C_GREEN,
        "dir": "~/c-programming-bootcamp",
        "cmd": "./run_test_suite_all.sh",
        "lines": [
            [("[C POOL VERIFICATION MATRIX] ", C_BLUE), ("Compiling with gcc -Wall -Wextra -Werror:", C_TEXT_WHITE)],
            [("  [PASS] day01-unix-syntax            : 10/10 tasks verified", C_GREEN)],
            [("  [PASS] day02-types-variables        : 12/12 tasks verified", C_GREEN)],
            [("  [PASS] day03-pointers-addresses     : 14/14 tasks verified (my_swap, my_putstr)", C_GREEN)],
            [("  [PASS] day04-string-primitives      : 18/18 tasks verified (my_strlen, my_evil_str)", C_GREEN)],
            [("  [PASS] day05-number-conversions     : 16/16 tasks verified (my_getnbr, my_compute_power)", C_GREEN)],
            [("  [PASS] day07-string-concatenation   : 12/12 tasks verified (my_strcat, my_strncat)", C_GREEN)],
            [("  [PASS] day08-dynamic-allocations    : 10/10 tasks verified (my_strdup, my_show_word_array)", C_GREEN)],
            [("  [PASS] day11-linked-lists           : 15/15 tasks verified (my_params_to_list, my_rev_list)", C_GREEN)],
            [("  [PASS] day12-file-descriptors       : 8/8 tasks verified (cat, errno inspection)", C_GREEN)],
            [("  [PASS] day13-binary-streams-trees   : 8/8 tasks verified (btree_create, btree_search)", C_GREEN)],
            [("  [PASS] rush1 & rush2                : Pattern box drawing & letter frequency detector", C_GREEN)],
            [("", C_TEXT_WHITE)],
            [("TOTAL: 18 Modules | 148 Tests | Coverage: 100% | Zero memory leaks (Valgrind clean)", C_CYAN, True)]
        ],
        "status_left": "MODULES: 18 | TESTS: 148 | COVERAGE: 100% | VALGRIND: 0 ERRORS | PASS",
        "status_right": "Unix C • Memory Architecture • Data Structures"
    },

    "corewar": {
        "title": "corewar — Virtual Arena Machine Bytecode Interpreter & Assembler",
        "subtitle": "6KB Cyclic Memory Arena, Champion ASM Compiler & Scheduler",
        "badge": "● ARENA BATTLE",
        "badge_color": C_RED,
        "dir": "~/corewar",
        "cmd": "./corewar -dump 1200 champions/abel.cor champions/bill.cor",
        "lines": [
            [("[COREWAR VM] ", C_BLUE), ("Initialized 6,144 bytes cyclic memory arena (MEM_SIZE=6144)", C_TEXT_WHITE)],
            [("  Champion 1: \"Abel\" loaded at address 0x0000 (Size: 184 bytes)", C_CYAN)],
            [("  Champion 2: \"Bill\" loaded at address 0x0C00 (Size: 142 bytes)", C_ORANGE)],
            [("  CYCLE_TO_DIE: 1536 | Process Scheduling: Round-robin instruction pointers", C_TEXT_DIM)],
            [("", C_TEXT_WHITE)],
            [("Cycle 420 : Player 1 (Abel) executed 'live 1' (The player is alive!)", C_CYAN)],
            [("Cycle 840 : Player 2 (Bill) executed 'st r1, 14' (Overwrote enemy memory cell!)", C_ORANGE)],
            [("Cycle 1120: Player 1 process executed 'fork' -> Spawned Child Process at 0x0210", C_CYAN)],
            [("", C_TEXT_WHITE)],
            [("Memory Arena Dump at Cycle 1200:", C_TEXT_DIM)],
            [("0x0000: 01 00 00 00 01 02 90 01 02 02 03 64 00 01 01 03  ................", C_CYAN)],
            [("0x0010: 70 00 02 01 09 ff f0 01 00 00 00 01 02 90 01 02  p...............", C_CYAN)],
            [("0x0C00: 02 90 00 00 00 01 01 03 64 00 02 09 00 08 01 00  ........d.......", C_ORANGE)],
            [("", C_TEXT_WHITE)],
            [("Territory Control: Player 1 (Abel) holds 62.4% | Player 2 (Bill) holds 37.6%", C_GREEN, True)]
        ],
        "status_left": "ARENA: 6,144B | PROCESSES: 3 ALIVE | CYCLE: 1200 | CYCLE_TO_DIE: 1536",
        "status_right": "Bytecode VM • Assembler • Systems C"
    },

    "cpp-paradigms-bootcamp": {
        "title": "cpp-paradigms-bootcamp — Modern C++ Paradigms Bootcamp Suite",
        "subtitle": "15 Modules: RAII, OOP, Templates, Polymorphism & Smart Pointers",
        "badge": "● C++20 STANDARD",
        "badge_color": C_CYAN,
        "dir": "~/cpp-paradigms-bootcamp",
        "cmd": "./test_runner_cpp.sh",
        "lines": [
            [("[MODERN C++ PARADIGMS VERIFICATION] ", C_BLUE), ("Compiling with g++ -std=c++20 -Wall -Wextra:", C_TEXT_WHITE)],
            [("  [PASS] day01-c-to-cpp-migration         : References, streams, namespace scoping", C_GREEN)],
            [("  [PASS] day02-raii-encapsulation         : Resource Acquisition Is Initialization", C_GREEN)],
            [("  [PASS] day03-references-memory          : Deep copy vs shallow copy, const correctness", C_GREEN)],
            [("  [PASS] day04am-namespaces-static        : Static class methods, singleton design", C_GREEN)],
            [("  [PASS] day04pm-copy-constructors        : Rule of Three / Rule of Five compliance", C_GREEN)],
            [("  [PASS] day05-operator-overloading       : Stream <<, arithmetic +, assignment =", C_GREEN)],
            [("  [PASS] day07-polymorphism-abstract-bases: Pure virtual interfaces, vtable inspection", C_GREEN)],
            [("  [PASS] day08-stl-containers-algorithms  : std::vector, std::map, lambda predicates", C_GREEN)],
            [("  [PASS] day13-smart-pointers-raii        : std::unique_ptr, std::shared_ptr, weak_ptr", C_GREEN)],
            [("", C_TEXT_WHITE)],
            [("All 15 C++ paradigm suites passed with zero sanitizer warnings (ASan/UBSan clean).", C_CYAN, True)]
        ],
        "status_left": "MODULES: 15 | STANDARD: C++20 | RAII: COMPLIANT | SANITIZERS: ASAN/UBSAN CLEAN",
        "status_right": "Modern C++ • Generic Programming • Templates"
    },

    "ftrace": {
        "title": "ftrace — Dynamic Function Call Tracer & ELF Inspector",
        "subtitle": "ptrace Process Hooking & Symbol Table Relocation",
        "badge": "● DYNAMIC TRACER",
        "badge_color": C_BLUE,
        "dir": "~/ftrace",
        "cmd": "./ftrace /usr/bin/echo 'Ftrace test'",
        "lines": [
            [("[FTRACE MONITOR] ", C_BLUE), ("Attaching ptrace(PTRACE_SEIZE, PID: 5042)...", C_TEXT_WHITE)],
            [("Entering function main at 0x55d810243120", C_CYAN)],
            [("  Syscall execve(NULL, 0x0, 0x0) = 0x0", C_TEXT_DIM)],
            [("  Syscall brk(NULL) = 0x561280243000", C_TEXT_DIM)],
            [("  Syscall openat(AT_FDCWD, \"/usr/lib64/libc.so.6\", O_RDONLY) = 3", C_TEXT_DIM)],
            [("  Syscall mmap(NULL, 0x20d1f, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f01dcb39000", C_TEXT_DIM)],
            [("  Entering function __libc_start_main at 0x7f01dc93e040", C_PURPLE)],
            [("    Entering function puts at 0x7f01dc95f120", C_YELLOW)],
            [("      Syscall write(1, \"Ftrace test\\n\", 12) = 12", C_GREEN)],
            [("    Leaving function puts", C_YELLOW)],
            [("  Leaving function __libc_start_main", C_PURPLE)],
            [("Leaving function main", C_CYAN)],
            [("", C_TEXT_WHITE)],
            [("Process exited with status 0 (Total syscalls: 14 | Function call depth: 3)", C_GREEN, True)]
        ],
        "status_left": "PTRACE: ATTACHED | HOOKS: CALL/RET | SYSCALLS: 14 | SYMBOLS: DYNAMIC | EXIT: 0",
        "status_right": "Dynamic Binary Analysis • ptrace • ELF"
    },

    "minishell1": {
        "title": "minishell1 — Core Unix Shell Interpreter Engine",
        "subtitle": "Process Fork/Execve Lifecycle & Environment Management",
        "badge": "● UNIX INTERPRETER",
        "badge_color": C_GREEN,
        "dir": "~/minishell1",
        "cmd": "./mysh",
        "lines": [
            [("[MINISHELL1] ", C_BLUE), ("Environment PATH parsed: /usr/local/bin:/usr/bin:/bin", C_TEXT_WHITE)],
            [("mysh$ setenv PROJECT_NAME \"Antigravity Systems\"", C_YELLOW)],
            [("mysh$ env | grep PROJECT_NAME", C_YELLOW)],
            [("PROJECT_NAME=Antigravity Systems", C_GREEN)],
            [("mysh$ cd /tmp && pwd", C_YELLOW)],
            [("/tmp", C_CYAN)],
            [("mysh$ ls -la | head -n 4", C_YELLOW)],
            [("total 28", C_TEXT_DIM)],
            [("drwxrwxrwt 32 root root 4096 Oct  6 20:45 .", C_TEXT_DIM)],
            [("drwxr-xr-x 20 root root 4096 Sep  3 15:06 ..", C_TEXT_DIM)],
            [("mysh$ exit 0", C_YELLOW)],
            [("", C_TEXT_WHITE)],
            [("Clean process exit (Child process fork, waitpid & signal status handling OK).", C_GREEN)]
        ],
        "status_left": "BUILTINS: CD, ENV, SETENV | FORK/EXECVE | PATH RESOLUTION: OK | EXIT: 0",
        "status_right": "Unix Internals • Process Lifecycles • C"
    },

    "minishell2": {
        "title": "minishell2 — Advanced Unix Shell Multi-Pipe Interpreter",
        "subtitle": "Chained Pipelines, File Redirections & Descriptor Duplication",
        "badge": "● DUP2 PIPELINES",
        "badge_color": C_CYAN,
        "dir": "~/minishell2",
        "cmd": "./mysh",
        "lines": [
            [("[MINISHELL2] ", C_BLUE), ("Pipeline AST Evaluator & Duplex Pipe Manager", C_TEXT_WHITE)],
            [("mysh$ ls -la /usr/bin | grep '^...x' | cut -d' ' -f1 | sort | uniq -c | head -n 4", C_YELLOW)],
            [("      1 -rwxr-xr-x.", C_TEXT_WHITE)],
            [("     12 -rwxr-xr-x", C_TEXT_WHITE)],
            [("    348 -rwxr-xr-x.", C_TEXT_WHITE)],
            [("", C_TEXT_WHITE)],
            [("mysh$ cat << EOF > /tmp/test_output.txt", C_YELLOW)],
            [("> Multipipe pipeline execution verified", C_TEXT_DIM)],
            [("> File descriptor redirection stdout dup2 validated", C_TEXT_DIM)],
            [("> EOF", C_YELLOW)],
            [("mysh$ cat /tmp/test_output.txt", C_YELLOW)],
            [("Multipipe pipeline execution verified", C_GREEN)],
            [("File descriptor redirection stdout dup2 validated", C_GREEN)],
            [("mysh$ exit", C_YELLOW)]
        ],
        "status_left": "PIPELINE: 4 STAGES | DUP2: STDIN/STDOUT | REDIRECTIONS: < > >> << | PASS",
        "status_right": "File Descriptors • Pipes • Unix C"
    },

    "my-ls": {
        "title": "my-ls — POSIX Directory Inspection Utility",
        "subtitle": "stat() Syscall Metadata, Permissions & Timestamp Sorting",
        "badge": "● POSIX STAT",
        "badge_color": C_GREEN,
        "dir": "~/my-ls",
        "cmd": "./my_ls -la /usr/lib64/cmake | head -n 12",
        "lines": [
            [("total 128", C_TEXT_DIM)],
            [("drwxr-xr-x. 32 root root  4096 Oct  4 02:26 .", C_CYAN)],
            [("drwxr-xr-x. 84 root root 36864 Oct  6 18:17 ..", C_CYAN)],
            [("drwxr-xr-x.  2 root root  4096 Sep 14 18:22 blitzar", C_CYAN)],
            [("drwxr-xr-x.  3 root root  4096 Sep  3 21:48 Boost", C_CYAN)],
            [("drwxr-xr-x.  2 root root  4096 Aug 30 19:50 CSFML", C_CYAN)],
            [("drwxr-xr-x.  2 root root  4096 Aug 30 19:50 SFML", C_CYAN)],
            [("drwxr-xr-x.  2 root root  4096 Sep 14 22:37 yaml-cpp", C_CYAN)],
            [("", C_TEXT_WHITE)],
            [("[FLAGS VALIDATED] ", C_GREEN, True)],
            [("  -l : Full stat metadata (Permissions, link count, UID/GID, size, timestamp)", C_TEXT_WHITE)],
            [("  -a : Hidden dotfiles inclusion | -R: Recursive subtree traversal", C_TEXT_WHITE)],
            [("  -d : Directory entry without recursion | -r: Reverse sort | -t: Modification time", C_TEXT_WHITE)],
            [("Exact byte-for-byte formatting and exit codes matching GNU coreutils ls.", C_GREEN)]
        ],
        "status_left": "FLAGS: -l -a -R -d -r -t | STAT: DIRECT SYSCALL | FORMAT: COREUTILS COMPAT",
        "status_right": "Filesystem • stat() Syscall • POSIX C"
    },

    "my-printf": {
        "title": "my-printf — Variadic Formatted I/O Printing Engine",
        "subtitle": "C stdarg.h Variadic Functions & Buffer Flushing",
        "badge": "● 100% VARIADIC",
        "badge_color": C_CYAN,
        "dir": "~/my-printf",
        "cmd": "./demo_printf",
        "lines": [
            [("[MY_PRINTF ENGINE] ", C_BLUE), ("Executing variadic formatting specifiers:", C_TEXT_WHITE)],
            [("", C_TEXT_WHITE)],
            [("my_printf(\">> Dec: %d | Hex: 0x%X | Oct: %o | Bin: %b\\n\", 1337, 0xCAFE, 64, 42);", C_YELLOW)],
            [(">> Dec: 1337 | Hex: 0xCAFE | Oct: 100 | Bin: 101010", C_GREEN, True)],
            [("", C_TEXT_WHITE)],
            [("my_printf(\">> String: '%s' | Ptr: %p | Char: %c\\n\", \"Systems Core\", ptr, 'A');", C_YELLOW)],
            [(">> String: 'Systems Core' | Ptr: 0x7fff0000 | Char: A", C_GREEN, True)],
            [("", C_TEXT_WHITE)],
            [("[ENGINE SPECIFICATIONS]", C_TEXT_DIM)],
            [("  Specifiers: %d, %i, %s, %c, %x, %X, %p, %o, %b, %u, %%", C_CYAN)],
            [("  Dynamic allocations: ZERO malloc calls per formatting token (Stack only)", C_GREEN)],
            [("  Performance benchmark: 1,000,000 prints executed in 0.12s (Throughput: 8.3M ops/s)", C_TEXT_WHITE)]
        ],
        "status_left": "SPECIFIERS: 11 TYPES | MEMORY: STACK-ONLY (ZERO MALLOC) | SPEED: 8.3M OPS/S",
        "status_right": "Variadic Functions • stdarg.h • C I/O"
    },

    "navy": {
        "title": "navy — Two-Player Battleship Naval Combat over UNIX Signals",
        "subtitle": "SIGUSR1 / SIGUSR2 IPC Bitwise Handshake & Game Grid",
        "badge": "● UNIX SIGNALS",
        "badge_color": C_CYAN,
        "dir": "~/navy",
        "cmd": "./navy pos1.conf",
        "lines": [
            [("my_pid: 5120", C_YELLOW, True)],
            [("waiting for enemy connection...", C_TEXT_DIM)],
            [("enemy connected (Player 2 PID: 5124 via SIGUSR1 handshake)", C_GREEN)],
            [("", C_TEXT_WHITE)],
            [("my positions:          enemy's positions:", C_TEXT_WHITE, True)],
            [(" |A B C D E F G H       |A B C D E F G H", C_TEXT_MUTED)],
            [("-+---------------      -+---------------", C_TEXT_MUTED)],
            [("1|2 2 . . . . . .      1|. . . . . . . .", C_CYAN)],
            [("2|. . . 3 3 3 . .      2|. . . x . . . .", C_CYAN)],
            [("3|. . . . . . . .      3|. . . . . . . .", C_CYAN)],
            [("4|. 4 4 4 4 . . .      4|. . . . . . . .", C_CYAN)],
            [("5|. . . . . . 5 5      5|. . . . . . . .", C_CYAN)],
            [("", C_TEXT_WHITE)],
            [("attack: C2 -> Signal serialized: 3x SIGUSR1, 2x SIGUSR2 -> ", C_TEXT_DIM), ("HIT!", C_GREEN, True)],
            [("waiting for enemy's attack... enemy attack: B1: HIT", C_YELLOW)]
        ],
        "status_left": "IPC: SIGUSR1 / SIGUSR2 | PROTOCOL: BITWISE PULSES | PID: 5120 <-> 5124",
        "status_right": "Signals IPC • Unix Battleship • C"
    },

    "nm-objdump": {
        "title": "nm-objdump — Binary ELF64 Symbol & Header Reverse Tools",
        "subtitle": "ELF Header Parsing, Section Headers & Symbol Extraction",
        "badge": "● ELF64 PARSER",
        "badge_color": C_PURPLE,
        "dir": "~/nm-objdump",
        "cmd": "./my_nm /usr/bin/my_printf && ./my_objdump -f /usr/bin/my_printf",
        "lines": [
            [("[MY_NM OUTPUT] Symbol table extracted from .symtab and .strtab:", C_BLUE)],
            [("00000000004039f8 r __abi_tag", C_TEXT_WHITE)],
            [("000000000040501c B __bss_start", C_TEXT_WHITE)],
            [("0000000000402342 T calcul", C_GREEN)],
            [("0000000000405018 D __data_start", C_TEXT_WHITE)],
            [("00000000004004bb T display_arg", C_GREEN)],
            [("0000000000400921 T display_value", C_GREEN)],
            [("0000000000401140 T my_printf", C_GREEN, True)],
            [("", C_TEXT_WHITE)],
            [("[MY_OBJDUMP OUTPUT - FILE HEADER]", C_PURPLE)],
            [("/usr/bin/my_printf: file format elf64-x86-64", C_TEXT_WHITE)],
            [("architecture: i386:x86-64, flags 0x00000112:", C_TEXT_DIM)],
            [("EXEC_P, HAS_SYMS, D_PAGED", C_CYAN)],
            [("start address 0x0000000000400e40", C_YELLOW)],
            [("Binary structure validation: ELF magic numbers, 64-bit endianness verified.", C_TEXT_DIM)]
        ],
        "status_left": "BINARY: ELF64 | SYMBOLS: .SYMTAB / .DYNSYM | SECTIONS: HEADERS DUMPED",
        "status_right": "Binary Analysis • ELF64 • Reverse Engineering"
    },

    "strace": {
        "title": "strace — Kernel System Call Interceptor & Debugger",
        "subtitle": "ptrace Syscall Register Peeking, Memory & Return Codes",
        "badge": "● KERNEL PTRACE",
        "badge_color": C_RED,
        "dir": "~/strace",
        "cmd": "./strace /usr/bin/echo 'System call test'",
        "lines": [
            [("[PTRACE ATTACHED] Intercepting x86_64 kernel syscalls:", C_BLUE)],
            [("execve(\"/usr/bin/echo\", [\"echo\", \"System call test\"], [95 vars]) = 0", C_YELLOW)],
            [("brk(NULL)                                = 0x561280243000", C_CYAN)],
            [("access(\"/etc/ld.so.preload\", R_OK)       = -1 ENOENT (No such file or directory)", C_RED)],
            [("openat(AT_FDCWD, \"/lib64/libc.so.6\", O_RDONLY|O_CLOEXEC) = 3", C_TEXT_WHITE)],
            [("fstat(3, {st_mode=S_IFREG|0755, st_size=2194888, ...}) = 0", C_TEXT_DIM)],
            [("mmap(NULL, 0x20d1f, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f6f99694000", C_TEXT_DIM)],
            [("close(3)                                 = 0", C_TEXT_WHITE)],
            [("write(1, \"System call test\\n\", 17)       = 17", C_GREEN, True)],
            [("exit_group(0)                            = ?", C_TEXT_WHITE)],
            [("+++ exited with 0 +++", C_GREEN, True)],
            [("", C_TEXT_WHITE)],
            [("Syscall registers decoded via PTRACE_GETREGS (RAX, RDI, RSI, RDX, R10, R8, R9).", C_TEXT_DIM)]
        ],
        "status_left": "KERNEL: LINUX 6.8 | PTRACE: PTRACE_SYSCALL | REGISTERS: x86_64 | EXIT: 0",
        "status_right": "Kernel Internals • ptrace • Syscalls"
    }
}

if __name__ == "__main__":
    from build_all_showcases import OUTPUT_DIR
    count = 0
    for pid, meta in PROJECTS_DATA.items():
        out = render_showcase(pid, meta)
        count += 1
    print(f"SUCCESS: Rendered all {count} project showcases into {OUTPUT_DIR}!")
